### ISSUE TITLE
Buyer-Countered text display

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#106]
Manage Offer Details: 
* Buyercountered needs to read 'Buyer-Countered'.

Screeshot:
![buyercountered-screenshot](https://cloud.githubusercontent.com/assets/7711293/6628216/a02d0a8e-c8d1-11e4-8601-f6c7b4b5911a.PNG)

**Comment by angelleye** [comment]
![image](https://cloud.githubusercontent.com/assets/629241/7104555/1cb974ac-e0b0-11e4-8188-e62e909b3b95.png)
