### ISSUE TITLE
Conflict with WooCommerce 2.3.6 and 2.3.7

### ISSUE THREAD

**Issue by djstallion** [angelleye/offers-for-woocommerce#109]
Fatal error: Cannot redeclare woocommerce_quantity_input() (previously declared in /.../wp-content/plugins/woocommerce/includes/wc-template-functions.php:860) in /.../wp-content/plugins/offers-for-woocommerce/offers-for-woocommerce.php on line 93

**Comment by djstallion** [comment]
Dev version have no conflict, only public beta have.

**Comment by angelleye** [comment]
I'm pretty sure we have this fixed in our current dev branch.  Do you want to download that and give it a shot?

**Comment by angelleye** [comment]
Oh, I guess you already said that.  :)

So yeah, we resolved that here already. I just need to get our 1.0.4 update released, which will be done early next week.

**Comment by djstallion** [comment]
Very good, I'll be wait :)

**Comment by angelleye** [comment]
If you just want to use the dev branch for now that should work fine for you until we get the official 1.0 released.
