### ISSUE TITLE
Offer lightbox pops up when it shouldn't.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#112]
From the Shop page, if I click on Make Offer there it takes me directly to the product page with the offer lightbox displayed.

If I click out of the lightbox at that point without making an offer, and then click Add to Cart, the lightbox pops up again after the item is added to the cart.

**Comment by kcwebmedia** [comment]
If class 'div.woocommerce-message' is found, then no scroll / no focus offer form.

**Comment by kcwebmedia** [comment]
This needs to account for woocommerce-error as well.
