### ISSUE TITLE
Bugs in code (v1.0)

### ISSUE THREAD

**Issue by djstallion** [angelleye/offers-for-woocommerce#114]
Thank You for the updated plugin!

I have found some bugs in code what causing also HTML5 validation errors

File: /public/views/public.php

Lines 94, 98, 102: duplicate ID "woocommerce-make-offer-form-label"
Change id="woocommerce-make-offer-form-label" to class="woocommerce-make-offer-form-label"
You can't have duplicate ID-s, but you can have duplicate classes

Line 110 and 111: Label "for" and "id" values doesn't match
Change id="angelleye-offer-notes" to id="offer-notes" or change

Line 111: unneeded self-closing syntax "/"

Line 72: unclosed div (closing div have to be in line 116-117)

I have done all these changes and plugin still works as before, but HTML5 validation errors are gone.

Last bug with admin "New offer email" setting:
If Recipient(s) field is empty no email received to defaults. Customer will got email.
Maybe same issue with "New counter offer" defaults too (no tested).

**Comment by angelleye** [comment]
Thanks for the feedback.  I'll check these issues out and get a patch released soon.

**Comment by angelleye** [comment]
Just pushed a 1.0.1 update that resolves these issues.  Thanks again for bringing that to our attention.

In the future feel free to submit a pull request here if you fix things.  We'll be happy to merge it in and make you a contributor!

**Comment by djstallion** [comment]
Very good, thank you for quick fixes! I have not much coding skills, but If I can help and make this plugin better, I will do this gladly!
