### ISSUE TITLE
Button not displaying

### ISSUE THREAD

**Issue by sicknickel** [angelleye/offers-for-woocommerce#117]
Howdy,

For some reason or another I cannot get the button to display. I've switched themes - no luck.

I've deactivated all plugins (except the needed ones) - no luck.

So, I don't know - if a link would help - here's one: https://thewildpetunia.com/store/electronics/15-pixma-ink-cartridges-compatible-032015-inkjet-mixed-lot-pgi-220bk-pink/

I appreciate it!

**Comment by kcwebmedia** [comment]
**SICKNICKEL**
* Check to see if the product has 'Offers' setting turned on (located in woocommerce setup tabs within edit product screen in WP admin).

Do any of the products show make offer button? Or is nothing working? Are you sure that the plugin is 'activated'?

**Comment by angelleye** [comment]
Sounds to me like you need to activate the offer on the product.  Right now you  have to do that one product at a time.  We're currently working to add a feature that will let you enable the offer button on multiple products at once.  That should be ready in a couple of weeks, but until then you'll have to do it one at a time.

Let us know if that's the case, though, or if you can't find that option.

**Comment by sicknickel** [comment]
@angelleye - ah, nice! That worked!

I must have missed a step in there - I appreciate the rapid response.

Looking forward to the update that allows you to change it for all product!

All the best.

**Comment by angelleye** [comment]
@sicknickel,

It should be available very soon.  I'm going to go ahead and close this issue but let me know if you have any other questions, and just keep your eye out for that update.
