### ISSUE TITLE
check i18n throughout plugin

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#119]
Go through all files to ensure Internationalization output in all cases.

**Comment by angelleye** [comment]
Need to make sure you fully understand how to use the i18n methods.  I see in some places you're using __() or _e(), but you're not including the second parameter, which is required, like this.

```
$hello =  __( 'Hello, dear user!', 'my-text-domain' );
```

In our case it looks like you've got $this->plugin_slug set and that's what you're using within the load_plugin_textdomain() method, so we would do something like this with all of our text output...

```
$hello =  __( 'Hello, dear user!', $this->plugin_slug );
```

**Comment by angelleye** [comment]
Did you say you had this one done?  I don't see any commit for it..??

**Comment by angelleye** [comment]
This one seems to be having the same conflict that #147 is having.  Fixing one may fix both, but I need you to take a look and keep what's necessary please.
