### ISSUE TITLE
Individually sold items

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#120]
Don't allow admin save offer qty > 1 if product sold individually
* If product is flagged 'sold individually', then show admin warning msg and prevent save as 'accepted' or 'countered' ( QTY must be 1 )

Prevent buyer from add offer to cart on offer that is qty > 1 if product sold individually
* Show buyer error msg
* Trash the offer

**Comment by cedarhillgoods** [comment]
Dupe of #118

**Comment by cedarhillgoods** [comment]
Should be closed.  Fixed in 1.1.0
