### ISSUE TITLE
Offers list action buttons display

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#121]
Action buttons on grid/list of offers get broken into two lines if resolution/width not large.
* Solution would be to fix the float or clear CSS styles on the action links. OR to 'fix' the width of first column to always fix (@ spec. resolutions).

**Comment by kcwebmedia** [comment]
Better would be to move the buttons to the last column

**Comment by angelleye** [comment]
This doesn't seem to be working for me.  The buttons do show up in the right column, but they still break at certain points when resizing the window, and they completely disappear at points, too.

[Here's a video demo](http://fiber.angelleye.com/temp/offers-for-woocommerce/GH-121.mp4).
