### ISSUE TITLE
Option for automatic email when offer comes in

### ISSUE THREAD

**Issue by cedarhillgoods** [angelleye/offers-for-woocommerce#124]
There should be an option available (global or per product) whereby an email is automatically sent to the shop owner when an offer comes in.  That way the owner can immediately be notified and respond via mobile phone email if they are on the go.

**Comment by angelleye** [comment]
That should be working that way already, actually.  Are you seeing any emails at all from the offers plugin when testing submitting offers?  The buyer should get a notification and the site admin should get a notification.  You could also set separate emails for each email type through the WooCommerce -> Settings -> Emails tab.

**Comment by cedarhillgoods** [comment]
Oh my bad.  The offers were getting put into spam mail.  I guess can't really do anything about that on this side.

**Comment by angelleye** [comment]
You could add the sender email to your whitelist, or add the entire domain.
