### ISSUE TITLE
Potential bug/conflict with Envato WordPress Toolkit.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#131]
A user who had the Envato WordPress Toolkit plugin installed was getting this error on the product / offer form page, so the jQuery wasn't working correctly.

```
Uncaught Error: You must initialize autoNumeric('init', {options}) prior to calling the 'get' method

/wp-content/plugins/envato-wordpress-toolkit/public/assets/js/autoNumeric-1-9-24.js?ver=4.0.1
```

We need to make sure this isn't a problem with our plugin that could conflict with other plugins, too.

**Comment by kcwebmedia** [comment]
The 'envato wordpress toolkit' plugin does not contain the autoNumeric javascript plugin. Maybe it used to or this user has added to it. 

https://github.com/envato/envato-wordpress-toolkit

After testing that plugin no conflicts found. Furthermore, within the Offers plugin each 'get' is proceeded by an 'init' when using the autoNumeric plugin. The error described above by that user does not seem to be related to the Offers plugin and the user should consider updating the envato plugin to latest build.

**Comment by angelleye** [comment]
Ok, thanks for looking into it.
