### ISSUE TITLE
Email template overrides

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#146]
Need to make email templates able to override with custom template theme. Right now the email settings do not allow an override.

**Comment by angelleye** [comment]
I guess I'm  not sure how to test this one.  If I was going to override an email template in WooCommerce I could copy the email template out of WC's directory into my theme's structure.  Where do I copy the original from for this plugin?  How do I know what to start with for creating my own email template?

**Comment by angelleye** [comment]
Ah, I see /admin/includes/emails/, so I guess that would be what I copy into my theme..??  What structure would it go in the theme, though?  Would it be /wp-content/themes/my_child_theme/offers-for-woocommerce/emails/woocommerce-offer-accepted.php, for example?  Or what?
