### ISSUE TITLE
Expiration Date Validation Notice Problem

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#149]
I just submitted a counter-offer which included an expiration date that is a week from now, however, after submitting the update I received a notice that the expiration date has already passed, which it clearly hasn't.

![image](https://cloud.githubusercontent.com/assets/629241/7494747/28329142-f3cf-11e4-93c1-8fa3a4d516f7.png)

Also, you used "past" in the message and that should be "passed".

**Comment by angelleye** [comment]
When I leave the details page and come back the message does not show up again, so it just seems to pop up right after updating the record with a counter offer even though it's not actually passed.

**Comment by angelleye** [comment]
Hmmm...I take that back.  Now it seems to be showing up even when I leave and come back.

**Comment by angelleye** [comment]
I went ahead and fixed the spelling of the word.

**Comment by kcwebmedia** [comment]
**When tested -- Cannot reproduce this issue.** Please verify you have uploading and running the latest version of the admin class, admin js, and summary view.

**Comment by kcwebmedia** [comment]
You said you fixed the spelling of the word, but I did not see commit for that. Should I make another commit for it?

**Comment by angelleye** [comment]
No, I must have just forgotten to reference this issue when I fixed it.

**Comment by angelleye** [comment]
This doesn't seem to be happening now, so maybe I wasn't fully updated or had caching issue.
