### ISSUE TITLE
Stock Validation Problem..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#150]
I currently have the option set to limit offer qty based on stock qty.

![image](https://cloud.githubusercontent.com/assets/629241/7494818/9f6f2824-f3cf-11e4-956b-c1a0de27423c.png)

I have a product setup where I have stock at 0 and backorder set to NOT allow.

![image](https://cloud.githubusercontent.com/assets/629241/7494837/bb03700e-f3cf-11e4-9832-0301e1a0cd01.png)

However, I am still able to submit an offer on this product.

![image](https://cloud.githubusercontent.com/assets/629241/7494852/d3442942-f3cf-11e4-91b9-f5ea8f915662.png)

**Comment by kcwebmedia** [comment]
I think on this issue you should test again... you may have not had the updated public class uploaded. 

**I cannot reproduce your issue.** I tested with a simple product - Setup to manage stock with stock amt. of 0, and do not allow backorder. - Result was no offer button or form. Worked correctly for me.

**Comment by angelleye** [comment]
I guess that must have been the case.
