### ISSUE TITLE
Plugin links placement

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#151]
On plugins.php screen - The plugin links no longer display with the WP 4.2 version of the plugins page.
* Move plugin links to the 'description' column after 'view details' link.

**Comment by angelleye** [comment]
What links are you referring to?  I'm still seeing the action links as expected.

![image](https://cloud.githubusercontent.com/assets/629241/7571290/4373336a-f7dc-11e4-8f8d-0fc008956936.png)

**Comment by kcwebmedia** [comment]
I do not have it showing on any plugins after latest WP update

Are you on current WP version?
Try to deactivate/active the plugin and see if it still works.

![screenshot from 2015-05-11 12 55 18](https://cloud.githubusercontent.com/assets/7711293/7571409/0c74fc3a-f7dd-11e4-90f2-1f172d2240a5.png)

**Comment by angelleye** [comment]
Yes, I am on 4.2.2 and I do not have this issue with any of my plugins.

**Comment by kcwebmedia** [comment]
OK. I will assume one of my plugins is causing this. I'll investigate.

**Comment by kcwebmedia** [comment]
Are you on WP admin with network enabled (multi-site) ?

**Comment by angelleye** [comment]
No, I do not have multisite enabled.

**Comment by kcwebmedia** [comment]
I see it works on the 'PayPal for WooCommerce' plugin, but it is not working on any other plugins that are installed. I also notice that WooCommerce plugin is utilizing the 'description' column for placing their plugin links.

![screenshot from 2015-05-11 13 48 01](https://cloud.githubusercontent.com/assets/7711293/7572538/892cb43c-f7e4-11e4-8c05-b186022af673.png)

**Comment by angelleye** [comment]
Yes, I noticed that they moved their's over there a while back, but again, as the screenshot I provided earlier shows, my plugins are all showing the action links just fine.

**Comment by angelleye** [comment]
Ah, I take that back.  Now that I've merged the 152 changes I see that it's not working anymore.

**Comment by angelleye** [comment]
hmmm...now I just switched back to my dev branch again and they're still now showing up again, but they were just fine prior to merging in these changes today, and they still work fine on other plugins, so we've done something to break it here.
