### ISSUE TITLE
Offers fail when product price is blank..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#156]
https://wordpress.org/support/topic/on-new-offer-uncaught-syntaxerror-unexpected-token?replies=15#post-6955892

**Comment by angelleye** [comment]
* If price is "blank" we need to hook something else so the offer button still shows up, and also make sure the offer form can pull necessary data to submit correctly.

* Needs to consider simple vs. variable products as well.  If variable products don't have any pricing then the same problem occurs.

**Comment by angelleye** [comment]
The offer works fine without a price now, however, you can't complete the checkout.  When I accept the offer and then click to buy from the accepted email, this is what I end up with.

![image](https://cloud.githubusercontent.com/assets/629241/7801204/99e4d004-02e6-11e5-8409-2b1dca880f95.png)

**Comment by angelleye** [comment]
We're also getting a PHP notice in the offer details when the price of the product is empty:

![image](https://cloud.githubusercontent.com/assets/629241/7801249/5d39ed50-02e7-11e5-86bb-21efbaa18d1e.png)

**Comment by angelleye** [comment]
This still isn't correct.  Now when I have a product with an empty price (not 0.00) the add to cart button still shows up on the page and is functional.  It just adds the item with 0.00, but unlike an actual 0.00 item it doesn't say FREE where the price would go.  

Also, not sure if it's because of the add to cart button or what, but the styling with the offer button is messed up.

![image](https://cloud.githubusercontent.com/assets/629241/7869885/2681545e-054b-11e5-8a31-21b5eaadaf8b.png)

**Comment by angelleye** [comment]
Functionally this seems ok now, however, we still have a confusing message getting displayed to the user after using the "Click to Pay" button from their accepted offer email.

![image](https://cloud.githubusercontent.com/assets/629241/7890735/62af3672-060d-11e5-9b93-23e480a1ee5d.png)

So I know you said it's removing the item and then you're just adding it right back in, but we can't just leave this error message telling them it can't be purchased.  That will be very confusing and people won't complete the checkout if they see that.

**Comment by angelleye** [comment]
Same thing shows up on the checkout page, too.

![image](https://cloud.githubusercontent.com/assets/629241/7890780/b1ef4542-060d-11e5-967d-9a1ecdc5c3a5.png)

**Comment by angelleye** [comment]
I still can't even complete the order, either, if I ignore the errors.  When I click Place Order it just sends me back to the top of the checkout page with the same message that the item has been removed.

**Comment by angelleye** [comment]
Here's another guy who is requesting this:  https://wordpress.org/support/topic/button-not-visible-on-all-products?replies=6

What's interesting here is that he's using an auction plugin (WooCommerce Simple Auctions) where he leaves the price blank so that the auction amounts can take over.  Somehow that plugin must be getting around the issues we've been running into, so we should study it to see what they may be doing to prevent the problems we've had.

**Comment by kcppdevelopers** [comment]
Can I have ( WooCommerce Simple Auctions ) to check this issue?

**Comment by angelleye** [comment]
I've asked the user that reported it to provide us with that plugin for testing purposes.

**Comment by angelleye** [comment]
According to @kcwebmedia the hooks have been added that will make this possible now.

**Comment by kcppdevelopers** [comment]
Can I have ( WooCommerce Simple Auctions ) to check this issue?

**Comment by angelleye** [comment]
@keyurptl Please review all of this and see if we can get this done easily now.  According to @kcwebmedia, WooCommerce did add the hook we needed at the time we tried this, so hopefully it'll be easy now.

**Comment by angelleye** [comment]
I believe we can  use this hook to get this done now:

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L809

**Comment by angelleye** [comment]
From Skype...

>[1:52:06 AM] Andrew Angell: so basically we need to use that hook to do the following...


>if($product_price == "" && $product_offer_enabled == true)
{
   $purchasable = true;
}
[1:52:28 AM] Andrew Angell: I think that alone would make our offer button show up, and would allow everything to function as expected.
[1:53:06 AM] Andrew Angell: those vars aren't exact, of course.
[1:53:19 AM] Andrew Angell: Just giving you a basic idea of what I think needs to happen.
[1:53:47 AM] Andrew Angell: It might actually make the add to cart button show up, too, which we would want to hide so that only our offer button shows up in these cases.

**Comment by angelleye** [comment]
Everything looks good with the actual offers now, so that part is fine.  Just a couple of things we need to address, though.

First, the Add to Cart button is still showing up.  That's what I was talking about in Skype.  

Our changes have basically allowed everything to work for the product even though it has no price.  When I click Add to Cart it just adds it at 0.00 as if 0.00 was actually set in the admin panel, but that's correct here.

In cases like this where the product has an empty value for the price, but it does have offers enabled, we need to make the Offer functional, but NOT the add to cart.

Second, when I view the offer in the admin panel, because it has an empty price I'm getting a message that says "Missing Meta Value" where it should be displaying the "Regular Price".

![image](https://cloud.githubusercontent.com/assets/629241/19718128/943e9b12-9b29-11e6-873b-4aec24d23fd1.png)

For this type of scenario, instead of "Missing Meta Value" I'd like that to say "Not Applicable"

**Comment by angelleye** [comment]
Need to follow up with this thread once we get this resolved:  https://wordpress.org/support/topic/remove-add-to-cart-button-issue

**Comment by angelleye** [comment]
I am still not able to complete the purchase of an accepted offer on products without prices.  Here is a video for your review:  http://fiber.angelleye.com/forums/github/offers-for-woocommerce/156.mp4

**Comment by angelleye** [comment]
Now when I load the product page for a product without any price I'm getting this...

![image](https://cloud.githubusercontent.com/assets/629241/21452423/5e0a5b00-c8cc-11e6-9f9e-021a8f5f32b3.png)

**Comment by angelleye** [comment]
@mdrahul 

This is working fine for me on products with a price...

![image](https://cloud.githubusercontent.com/assets/629241/21497658/305f4238-cbec-11e6-9611-5e44eac40313.png)

However, on products without a price the Highest Current Offer box is not showing up at all.

![image](https://cloud.githubusercontent.com/assets/629241/21497688/61574b24-cbec-11e6-9542-1f78bcb04b30.png)
