### ISSUE TITLE
add_to_cart_redirect filter is deprecated

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#162]
**Use woocommerce_add_to_cart_redirect instead**

**Comment by angelleye** [comment]
I'm doing a project-wide find for "add_to_cart_redirect" and it's not finding any..??

**Comment by kcwebmedia** [comment]
This is not OFWC related. I find it is coming from your PP for WC plugin
REF: https://github.com/search?q=user%3Aangelleye+add_to_cart_redirect&type=Code
