### ISSUE TITLE
public view "form" [request]

### ISSUE THREAD

**Issue by elarson** [angelleye/offers-for-woocommerce#167]
[Copy of my review on WordPress] I really like your plugin. I'm using it on a donation site for selling paintings to people who want to donate to a cause (disabled artist). We really did not want to price paintings and wanted a way that the artist could easily communicate with people wanting to donate. We've been able to configure almost everything the way we wanted it out-of-the-box.

Because of tax and implications and limits for income for disability benefits, we have a need to make sure that everything is done as a "donation" as opposed to a business transaction. I've sanitized the e-mail notifications easily (thanks for hooking in so well), but am more concerned about the public view "form" (offers-for-woocommerce\public\views\public.php). I have modified it, but am concerned about upgrades.

It would be nice to be able to copy it to a child theme much like how e-mail notifications are done, or have a form modification functionality in wp-admin. A front-end to respond to offers would also be nice, especially for someone who is disabled, but I can imagine that is a ways away. 

Here is a link to the website if you are interested: http://www.robertpit.com/paintings/

**Comment by angelleye** [comment]
Glad to see you were able to get it working the way you want for the most part.

We'll have to see about the options for overriding the public form.  We can possibly make it work the same way the email does, or we may just have to add some filter hooks so you can adjust the verbiage on the form.  

I'm still not fully understanding how managing the offer from the front-end would be any different than managing it on the back-end..??  Also, if it's available on the front end we'd still have to protect it from general users so they couldn't see pending/completed offers.  

Seems like overkill, but again, maybe I'm just not understanding what you're after..??

**Comment by angelleye** [comment]
There's an example here of what @elarson did to help, but we may be able to improve upon this.

**Comment by elarson** [comment]
About the front-end to respond to offers, I meant an easier way to get to the offers without going through the admin panel. After thinking about this more I think it is asking for a bit much, so don't feel you need to pursue this any more. The e-mail notifications with the link buttons to wp-admin are working well enough, It also helped to change the admin.css post status links to normal as mentioned in the other request.

**Comment by elarson** [comment]
Just to be clear, I am still *very* interested in options for overriding the public form.

**Comment by angelleye** [comment]
Yes, I have gotten other requests for this as well.  We'll definitely get it done.

**Comment by angelleye** [comment]
We decided to go with filter hooks for the form labels and the ability to add intro/outro paragraphs to the form.
