### ISSUE TITLE
admin.css post status links normal [request]

### ISSUE THREAD

**Issue by elarson** [angelleye/offers-for-woocommerce#169]
Would you please consider making all admin.css post status links normal and not just on hover when the user mouses over it? The reason for the request is for web accessibility. 

Note, it's always a good idea if you use a hover to also add a focus for keyboards, but in this case, I think it would be better to have no link state.

**Comment by angelleye** [comment]
Are you referring to the pending, accepted, countered, etc. status?  There are filters across the top so you can easily view offers with a particular status, but I agree it would be nice to see on the main list without having to hover over the lines.

**Comment by elarson** [comment]
Yes, that is what I mean -- to display without needing to hover.
