### ISSUE TITLE
Display offer is pending [request]

### ISSUE THREAD

**Issue by elarson** [angelleye/offers-for-woocommerce#172]
We would like to be able to display that an offer is pending if an offer has been accepted, it is limited by the product stock quantity, and possibly that it is is within the offer expiration date, until the order has been paid.  

Our use case scenario is a donation site for a handicapped artist selling paintings. All paintings have an inventory of "1" with "Limit Offer Quantity at Product Stock Quantity". When a user makes an offer that would bring the stock quantity to "0" we would like to display "THIS PAINTING HAS AN OFFER PENDING", which would remain in that state until the offer expiration date or a payment has been made. 

We have the following in the functions.php to show availability based on a painting being in or out of stock and we would like to enhance it:

```
add_filter( 'woocommerce_get_availability', 'custom_get_availability', 1, 2);
  
function custom_get_availability( $availability, $_product ) {
    //change text "In Stock' to 'AVAILABLE'
    if ( $_product->is_in_stock() ) $availability['availability'] = __('THIS PAINTING IS AVAILABLE', 'woocommerce');
  
    //change text "Out of Stock' to 'SOLD'
    if ( !$_product->is_in_stock() ) $availability['availability'] = __('THIS PAINTING IS SOLD', 'woocommerce');
        return $availability;
    }
```

**Comment by angelleye** [comment]
@kcwebmedia They should be able to do this currently, right?  I'm thinking some logic to be added to his custom_get_availability() method that checks if the product has a pending offer, and then react accordingly..??

**Comment by elarson** [comment]
Yes, the code snippet works currently. Your logic sounds right with a hook to a pending offer. Thanks for considering.

**Comment by angelleye** [comment]
@kcppdevelopers please review this and let me know your thoughts.  I'm still a little bit confused on if we need to add a new hook into our plugin or if his current custom function can be adjusted slightly to get what he wants done..??

**Comment by kcppdevelopers** [comment]
I have review the previous code and added some additional code as per requirement. <a href="http://chopapp.com/#s3mj9u1c">Here</a> is code, use this code in your function.php file.

**Comment by angelleye** [comment]
@elarson What do you think about what @kcppdevelopers provided?

**Comment by angelleye** [comment]
I'm going to close this issue because it doesn't seem to be anything we need to adjust in our code. 

@elarson, let me know if you have any questions about what @kcppdevelopers provided here.

**Comment by elarson** [comment]
I have tested this and it works perfectly. Many thanks @angelleye and @kcppdevelopers .

**Comment by angelleye** [comment]
Glad to hear it!
