### ISSUE TITLE
E-mail notifications {offer_number} {offer_date} [request]

### ISSUE THREAD

**Issue by elarson** [angelleye/offers-for-woocommerce#173]
In the subject line for e-mail notifications it would be nice to do something similar as in WooCommerce for {order_number} {order_date}, e.g., {offer_number} {offer_date}.

**Comment by angelleye** [comment]
I agree.  We'll make it happen!

**Comment by angelleye** [comment]
I see that this subject was applied to the email that gets sent to the buyer, but the email that goes to the site owner still has the original subject line.  Here they are together in my inbox after I just did a test offer.

![image](https://cloud.githubusercontent.com/assets/629241/10115488/21d3c4cc-63cf-11e5-9f5b-f452dc67c330.png)

Would like to apply the same changes to the email that goes to the site owner.
