### ISSUE TITLE
Conflict with 3rd Party Plugin

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#177]
When the Ajax Search Pro for WordPress plugin is enabled the Offers plugin returns an error in Firebug when submitting an offer:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) - http://gpmoto.de/produkt/4sr-lederkombi-rr-edition-black-silver-evo/?woocommerceoffer_post=1

The offer still submits just fine, but an error is returned to the user as if it failed.

**Comment by kcwebmedia** [comment]
I cannot reproduce this issue. Please check server error log to see what is causing the 500 error.

**Comment by kcppdevelopers** [comment]
I need "Ajax Search Pro for WordPress plugin" for testing this issue.

**Comment by kcppdevelopers** [comment]
I have checked with "Ajax Search Pro for WordPress plugin" on fresh setup it's working fine for me.
