### ISSUE TITLE
WooCommerce 2.4 Compatibility..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#189]
I just noticed that WooCommerce released an update for their Tab Manager plugin, and the only thing it shows in the changelog is "WooCommerce 2.4 compatibility."

Leads me to believe we may need to make some adjustments to our tab usage for WC 2.4.

**Comment by kcppdevelopers** [comment]
I have checked woocommerce 2.4.7 and WordPress 4.3.1 version, plugin is compatible with current version.
