### ISSUE TITLE
User Role based access to manage offers.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#190]
https://wordpress.org/support/topic/multi-seller-offer-administration

**Comment by kcwebmedia** [comment]
Shop Manager currently does have access to approve/decline offers from 
the offers list view. Also we have setting option in General Settings 
for choosing which user roles have access to it.

-- Does this need more features/logic? or do we already have this idea 
covered?

**Comment by angelleye** [comment]
The setting in general tab is for limiting offers to specific roles.  So only people in those roles can see offer buttons and make offers.

This is referring to the ability to administer the offers on the back-end.  The user said Shop Manager did not have the ability to manage the offers, but I'll double check with him.

**Comment by angelleye** [comment]
The user added more info about his request.  Take a look at the WP support thread.

**Comment by kcppdevelopers** [comment]
I have double check Shop Manager have ability to manage the offers.

**Comment by angelleye** [comment]
I think the shop manager role gives them access to deal with offers from within the admin panel, but he's not allowing his "shop managers" to login to the admin panel.  He still wants them to be able to manage their own offers, though.

I'm trying to clarify again with the user what exactly they're after here.

**Comment by angelleye** [comment]
I think we're good here, and if people want to do more with roles they could use a plugin like:  https://wordpress.org/plugins/capability-manager-enhanced/
