### ISSUE TITLE
Only show offer on exit.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#192]
* https://www.angelleye.com/support/scp/tickets.php?id=219

User requests a feature where they could enable the option to hide offers except when a user exits the site without buying.  Then a lightbox window would pop up with one of those messages like "wait, don't go yet!  Make an offer!"

We can set this up so it only triggers when product detail pages are being viewed.

At the product level we need to add a check box option to enable/disable this functionality.

If the option is enabled, offers would be hidden except for when the exit popup is triggered.  The popup should be able to display the same offer form that would typically go in the tab/lightbox under normal use, but the form would show up directly in the exit popup.

**Comment by angelleye** [comment]
@mdrahul Something strange is going on here.  I'm getting another merge conflict trying to get this into the dev branch, and this one seems like the entire page was copied in or something..??  The conflict covers almost the entire script.  I've never seen this sort of thing before, so I'm not sure what happened here.  Please merge dev into Issue#192 and get it worked out.

**Comment by mdrahul** [comment]
I have merged dev branch into issue#192.
