### ISSUE TITLE
Potential adjustment necessary for WC 2.4.7

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#195]
>Fix - Changed the way variable product prices get cached for greater plugin compatibility. See http://wp.me/p6wtcw-5x

I know we had to do some things to get variable products working well originally.  Not sure if this will affect anything that we'll need to adjust.  Need to check it out.

**Comment by kcppdevelopers** [comment]
I have checked woocommerce 2.4.7 and WordPress 4.3.1 version, plugin is compatible with current version.
