### ISSUE TITLE
Ability to add custom fields to offer form.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#199]
A customer is asking if there is a way to add a zip code field to the offer form (https://wordpress.org/support/topic/adding-field-to-form-list).  

I think it would be best if we add a hook where people can add any custom field they want to the offer form.  Of course, whatever they add should be carried through to the offer meta data and displayed on the offer details along with the other offer details.  Same goes for any email notifications that are sent.

**Comment by kcppdevelopers** [comment]
sample code for add custom fields to offer form: http://pastebin.com/h6jrk0ZT

**Comment by kcppdevelopers** [comment]
sample hook for add custom field to offer form: http://pastebin.com/cDQEWEhg
