### ISSUE TITLE
Counter-Offers

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#20]
* Site owner should have the ability to enter a counter-offer.  
* Again, they should have the ability to enter the qty and price (with defaults set to original offer).  Need to handle scenarios where they may want to accept the offer, but they don't have enough inventory to the originaloffer, for example.  
* Also, of course, may just come back with a different price on the qty requested.
* Also need the ability to add notes to the counter offer. 
* Offers system should get updated with counter-offer status and an email sent to the shopper with the counter-offer details.
* Shopper should have the ability to respond with another counter-offer or go ahead and click a button to load the cart with the counter-offer price that was sent.

**Comment by kcwebmedia** [comment]
This issue tested and ready for review.
