### ISSUE TITLE
User reported issue with multi-language items..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#204]
https://wordpress.org/support/topic/enable-offers-just-for-the-primary-product?replies=6#post-7742922

**Comment by kcppdevelopers** [comment]
I need wpml plugin to test this issue: https://wpml.org/purchase/

**Comment by angelleye** [comment]
Here is a copy of WPML to use for working this out.

[sitepress-multilingual-cms.3.5.3.zip](https://github.com/angelleye/offers-for-woocommerce/files/535475/sitepress-multilingual-cms.3.5.3.zip)

**Comment by keyurptl** [comment]
i installed "WPML" and then Install "WooCommerce Multilingual" to reproduce issue. but still need following Add ons.

WPML Translation Management,
WPML String Translation,
WPML Media

http://screencast.com/t/ojUbI2Xeovz

**Comment by angelleye** [comment]
Those add-ons should be available in this zip...

[WPML-Addons-0716.zip](https://github.com/angelleye/offers-for-woocommerce/files/537420/WPML-Addons-0716.zip)
