### ISSUE TITLE
Ability to accept / decline directly from the email.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#206]
Right now you have to click a button in an email which takes you to the offer details on the site for management.  Some users are requesting the ability to accept or decline offers directly from within the email body so they don't have to do anything in the offer details screen.

We could probably still open the details screen, but just add a URL param or something to trigger the automated action.

**Comment by kcppdevelopers** [comment]
http://screencast.com/t/BEdrmhPh5tE
