### ISSUE TITLE
Dokan MultiVendor Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#209]
https://wordpress.org/support/topic/plug-in-can-work-with-e-commerce-multi-vendor?replies=1#post-7791326

**Comment by angelleye** [comment]
This is done to the point of the emails going to the vendor, but we have not yet taken the time to fully integrate so that vendors could manage their own offers independently of each other.  

This is probably not something we're going to get done any time soon unless the Dokan plugin starts to grow rapidly.

**Comment by angelleye** [comment]
We're going to turn this into a premium extension.

**Comment by angelleye** [comment]
We were going to tie this int our WC Vendors plugin and rename it to MultiVendor so that it could support both.  The dokan (and YITH) vendor plugins are a little different, though, and were not tying in well, so we ditched that idea.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/OFW-70
