### ISSUE TITLE
Show pending offer(s) on front end.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#210]
When an item has an offer pending (either brand new, accepted but not paid, etc.) then display on the front end that x number of offers have been made and are pending on the item.  

This combined with the QTY available could entice people to go ahead and buy at full price, or submit their own offers more quickly.

Should also make this an option that the site owner can enable/disable.  Not everybody will want to display that, but many will.

**Comment by kcppdevelopers** [comment]
This might be same as #235

**Comment by angelleye** [comment]
The output of the message when enabled is showing up above the offer button...

![image](https://cloud.githubusercontent.com/assets/629241/16187093/34a568ee-3683-11e6-8e7f-05987f31f32f.png)

Can we make it show up after the button instead of before?

**Comment by angelleye** [comment]
Did you see my note here about adjusting the notice location?

**Comment by kcppdevelopers** [comment]
I have applied above changes and push to the issue branch.
