### ISSUE TITLE
Translation missing a particular line..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#211]
Report from user that the following cannot be translated:

>To make an offer please complete the form below:

Says everything else is translating fine, but that line isn't available.  Maybe we don't have it wrapped in localization logic correctly within the plugin, so it wasn't included in the PO file..??

https://www.angelleye.com/support/scp/tickets.php?id=327

**Comment by angelleye** [comment]
Another report about this line not translating correctly.

https://www.angelleye.com/support/scp/tickets.php?id=379

**Comment by kcppdevelopers** [comment]
this issue already done in ref #238
