### ISSUE TITLE
Custom Field Placement

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#212]
We added hooks so that people can include their own custom fields in the offer form, however, it's simply adding it to the very bottom and doesn't allow them to place their field(s) where they want.

Need to make this available.

https://wordpress.org/support/topic/add-zip-code-field?replies=12#post-7797195

**Comment by kcppdevelopers** [comment]
sample hook for add custom field to offer form: http://pastebin.com/cDQEWEhg
