### ISSUE TITLE
Bugs reported in 1.2.0

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#214]
>sorry to say but it's full of bugs...
offer is inclusive vat and countered offer the vat will be added as a exra bonus.

>accepted counter - counter offer is suddenly using the price of te first offer as a accepted offer?

>also it can not handle product addons for a offer.

>good luck!

https://wordpress.org/support/topic/array-bug-cookie-removal-and-a-request?replies=10

**Comment by angelleye** [comment]
I'll create the Product Add-Ons compatibility as a new issue / feature request.

**Comment by angelleye** [comment]
We are unable to reproduce these so far.  I've asked the user who reported these issues for more info.

**Comment by angelleye** [comment]
Feedback from the user...

>Ok angelleye, I have removed the w3 caching so the site is now using no caching. Everything works fine except when the counter offer is accepted the link in the email that put the product in the basket is adding VAT on top of the price. You should be able to reproduce this.

>Also I am still having the array bug:
Attributes: Notice: Array to string conversion in /home/xxxxxx/domains/xxxxxxx.nl/public_html/webshop/wp-content/plugins/offers-for-woocommerce/admin/views/meta-panel-summary.php on line 29 Notice: Array to string conversion in /home/xxxxxx/domains/xxxxxx.nl/public_html/webshop/wp-content/plugins/offers-for-woocommerce/admin/views/meta-panel-summary.php on line 29 Notice: Array to string conversion in /home/xxxxxx/domains/xxxxxx.nl/public_html/webshop/wp-content/plugins/offers-for-woocommerce/admin/views/meta-panel-summary.php on line 29 Array, Array, Array

**Comment by kcwebmedia** [comment]
As for the notice errors -- In that view the value needs to be checked for is_array() before assuming it is and imploding it. Basically !checks on those values before output is needed there.

**Comment by angelleye** [comment]
I'm going to move the VAT issue to its own issue on a future milestone.  

We just need to look into the PHP notices that are getting displayed and eliminate those for this issue.
