### ISSUE TITLE
Product Add Ons Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#215]
In #214 the user mentioned that offers do not work with product add-ons.  Let's go ahead and get this working so that it's compatible.

**Comment by angelleye** [comment]
Here is the extension you'll need for this issue.

[woocommerce-product-addons-2.7.26.zip](https://github.com/angelleye/offers-for-woocommerce/files/881394/woocommerce-product-addons-2.7.26.zip)

**Comment by tejasm-itpath** [comment]
Thanks  @angelleye
