### ISSUE TITLE
Ability to set shipping price in the offer flow.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#216]
Add the ability to set a shipping price when accepting or countering an offer.  So you would accept or the counter, but you could also set a value to use for shipping.  Then when the user checks out for the accepted/countered offer it would load the item at the correct price as well as the shipping at the correct price.

https://www.facebook.com/groups/advanced.woocommerce/1211895642158186/?notif_t=like

**Comment by angelleye** [comment]
I think there's something you needed to adjust here after the 2.6 update..??

**Comment by angelleye** [comment]
We have a user that just downloaded the release branch and is reporting a problem that I think stems from this issue (but I'm not 100% sure).

https://wordpress.org/support/topic/users-cant-check-out-shipping-offers-for-woocommerce?replies=2

**Comment by kcppdevelopers** [comment]
I have checked this issue in latest dev branch, for me everything is working fine,  though? Maybe user download before six day? Also please ask user about woo version.
