### ISSUE TITLE
WCVendors Integration

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#218]
Requested by Waldemar Bernedo via email.  Need to follow up with him when this is done.

Extend WCVendors to add the ability for vendors to manage their own offers.

>* Offers and relevant emails should be directed to the vendor (not admin) who has posted the item
* A location for the vendor to manage the offer (most likely another tab on the "WC Vendors" vendor dashboard)
* Also I would like the ability to remove the quantity and price each option, only one item is being posted on my site at a time

**Comment by angelleye** [comment]
We may just do this as a premium extension and it will turn into a separate plugin of its own.

**Comment by angelleye** [comment]
Info from user that wants this (farrelmobile @ gmail.com).  [This plugin](http://fiber.angelleye.com/forums/github/wc-vendors-pro-simple-auctions-v1.0.1.zip) can be used as a template to see how to get this integration done.

**Comment by heinvv** [comment]
Is it working now?

Or do you support any other multi vendor platforms?

**Comment by angelleye** [comment]
We have yet to begin work on this, unfortunately.  Hopefully soon!

**Comment by angelleye** [comment]
A private repo for WC Vendors integration has been setup here:  https://bitbucket.org/angelleye/offers-for-woocommerce-wc-vendors
