### ISSUE TITLE
jQuery Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#221]
At this site www.gspawn.com we get the following error when submitting the form:

![image](https://cloud.githubusercontent.com/assets/629241/12466973/b0dba642-bf9d-11e5-8d1c-0568868366cd.png)

The error is happening at /public/assets/js/public.js?ver=1.2.0, line 64.

**Comment by angelleye** [comment]
Here is the WordPress forum thread for the user:  https://wordpress.org/support/topic/make-an-offer-and-nothing-happens?replies=9

**Comment by angelleye** [comment]
I think what might be happening here is that the jQuery is getting messed up when it gets minified by a plugin they are using.

I have this problem myself with various features of angelleye.com when using the WP Rocket caching plugin.  Some jQuery gets broken when it gets minified, so then I have to go in and tell WP Rocket to ignore those specific jQuery files and leave them alone.  

I've told the user to see if they can do something similar, and see if it resolves the problem.  

I'd still like to look into this, though, and see if there's something we can adjust so that our jQuery doesn't get broken when minified.

**Comment by kcwebmedia** [comment]
When viewing the source of the page I notice that the public.js is being loaded before the jquery is loaded in the footer. This is why the jquery is breaking in public.js. Not sure if it is a theme issue or plugin issue or plugin conflict. Surely the enqueue of the public.js is set to rely on jquery first, but that doesn't seem to be the case in the source.

**Comment by angelleye** [comment]
Discovered that this user had this in the theme's functions.php file:

    // Load jQuery
    if ( !is_admin() ) {
       wp_deregister_script('jquery');
       wp_register_script('jquery', ("http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"),     false);
       wp_enqueue_script('jquery');
    }

When I comment those lines out and let WP load jQuery the usual way everything worked as expected.  

I am not sure if this user is doing something incorrectly here or why that change he made would have broken our code but not other plugins..??  

Seems like maybe there is something we need to adjust so that sort of change doesn't break our stuff, or is that just bad practice what they're doing?

**Comment by kcppdevelopers** [comment]
Seems like just bad practice what they're doing, if user want to register own copy or from the Google CDN then user should used "wp_enqueue_scripts" hook to deregister script.

<pre>
<code>
function mytheme_enqueue_scripts() {
       wp_deregister_script('jquery');
       wp_register_script('jquery', ("http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"),     false);
       wp_enqueue_script('jquery');
}
add_action('wp_enqueue_scripts', 'mytheme_enqueue_scripts');
</code>
</pre>
