### ISSUE TITLE
Emails don't send when user signed in as admin..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#222]
I'm getting lots of reports where people say that when they are signed in as an admin the emails don't send when submitting offers.

They say if they log out and do it again it works fine, but not when they are signed in as admin.

I don't know if it's just a signed in problem in general, or if it's an admin role only problem, or what, but we need to make sure the emails will send if they are signed in as admin while submitting an offer.

**Comment by kcwebmedia** [comment]
Somewhere along the way code was added to not include admins in the submit offer function on public. See this line: https://github.com/angelleye/offers-for-woocommerce/blob/release/public/class-offers-for-woocommerce.php#L849 

I need to understand why this was added before you just remove it.

**Comment by angelleye** [comment]
I can't think of any reason we would have done that.

**Comment by angelleye** [comment]
Need to follow up with this user when it's fixed:  https://www.angelleye.com/support/scp/tickets.php?id=367

**Comment by kcwebmedia** [comment]
On public class there was a commit that replaced !is_admin() check with !current_user_can('administrator'). **This is incorrect and is preventing the form from submitting the offer if logged in as admin.**

Diff: https://github.com/angelleye/offers-for-woocommerce/commit/19d5918c0e82c4d7234d8e22f5f38e8a7d679a3e#diff-13a4758c714adedb093dc77327b15a1cL876
Ref: #199

**Comment by angelleye** [comment]
So we don't need the original logic to ensure it doesn't load in the admin panel..??  Apparently that's what the if(!is_admin()) was doing originally, but then that was changed to what you have now removed.

Are you sure we didn't need !is_admin() to ensure the code wouldn't run while in the admin panel?

**Comment by kcppdevelopers** [comment]
Yes, I am sure new_offer_form_submit function code only run when Submit Offer button pressed.
