### ISSUE TITLE
Tax Improvements

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#223]
* https://wordpress.org/support/topic/not-showing-the-correct-price?replies=5#post-8771253

Right now we are not considering tax at all in the offers.  Whatever the offer accepted price ends up being, when the user checks out any tax rules that apply would be added to that.

We need to add an option for the administrator when accepting an offer to set whether or not the accepted offer price should be inclusive of tax or not. 

If the accepted offer does include tax, then we need to make sure when the buyer clicks to pay the tax amount is split out into the tax field and the actual item price updated accordingly so the total equals the accepted amount.

**Comment by angelleye** [comment]
Need to update this post once this is fixed:  https://wordpress.org/support/topic/not-showing-the-correct-price?replies=5#post-8771253

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/OFW-68
