### ISSUE TITLE
Generate fresh .pot default file.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#224]
[User reports](https://wordpress.org/support/topic/button-position-and-translation-issues?replies=2#post-7928722) that the message about submitting the form is not showing up in the po file for translation.

**Comment by kcppdevelopers** [comment]
Now inbuilt tool available for generate .POT file : https://developer.wordpress.org/plugins/internationalization/localization/#plugin-repository-admin-tools

**Comment by angelleye** [comment]
Yes, it's sort of backwards, though.  We can't use that until we have our updated code in the WordPress repo, but then we'll have to release a patch update behind that to include the updated .pot file.

Unless you can think of a better way..??
