### ISSUE TITLE
qTranslate-X - Some emails translate and others only output the shortcode..??

### ISSUE THREAD

**Issue by usbswiper** [angelleye/offers-for-woocommerce#225]
User report:  https://www.angelleye.com/support/scp/tickets.php?id=376

>I am using qTranslate-X with Offers for WooCommerce. E-mail notifications seem to work fine with qTranslate-X for New offer and Offer received. For New counter offer, Accepted offer, Declined offer, and Offer On Hold it is showing the shortcode. Here is an example of what is shown with English/Dutch: [:en]Text English[:nl]Text Dutch[:]. 

>I could not test the Offer note, because it is unclear to me when this is used. As I understand it, the notes are only sent with the status changes, in which case, the other e-mail notifications are used. Can you correct me if I am wrong about this.

**Comment by angelleye** [comment]
We need to review this, see if we can reproduce the problem with the emails, and then get the ones that aren't working properly fixed.

Seems like we did have an issue before where we fixed the ones that are working, so there must be some deliberate step that wasn't applied to all of the notifications.  I can't remember what issue it was, though.

**Comment by kcppdevelopers** [comment]
Some of email template we have not correct translate, now we have already resolved this issue in #238

**Comment by kcppdevelopers** [comment]
I have checked now everything is working fine with qTranslate-X plugin.
