### ISSUE TITLE
Declined Offer Coupons

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#23]
I think it might be a nice option to let the site owner decline an offer, but then choose to include any active coupon codes in the system in the email so the shopper can at least buy the item at that discount.

I'm thinking that part of the form where the site owner declines the offer could be an option to include a coupon code in the notification email they get.  So then they could choose from available coupons in their system to include with the email notification.

**Comment by angelleye** [comment]
I have merged the changes here, but I am not seeing the functionality.  When I decline an offer in my system I never see any place that gives me the option to include a coupon code in the declined offer email and choose which coupon I want to include..??

**Comment by angelleye** [comment]
This is still not working for me from the offers list view.  I just get the message that says "are you sure?" and if I say OK it declines it instantly.  No chance to set any coupon.

I do see in the offer details screen now that it provides a coupon drop down, however, the jQuery there seems to be screwed up now.

Immediately upon loading the offer details screen the options that would show up only for declining an offer are already showing, and the validation message about the expiration is displaying even though that expiration date has not been reached...

![image](https://cloud.githubusercontent.com/assets/629241/10299066/6ab72cb8-6bab-11e5-9434-1aa11ef2c843.png)

So again, I do see the ability to add a coupon here, but that shouldn't show up unless I've selected to decline the offer, and the validation shouldn't be showing because that date has not been reached.

**Comment by angelleye** [comment]
On this window...

![image](https://cloud.githubusercontent.com/assets/629241/10384545/696180a8-6e02-11e5-8ac9-f13f935efb00.png)

I'd like to add a basic instruction...

> Even though you are declining the offer, letting the buyer know you are willing to work with them can entice them to go ahead with a purchase.  Select a coupon code to include it with the declined offer email the potential buyer will receive.

**Comment by angelleye** [comment]
The declined offer email does include the code I selected, which is good...

![image](https://cloud.githubusercontent.com/assets/629241/10384583/1dd668dc-6e03-11e5-919e-0109d2cb0da2.png)

It doesn't stand out very much, though.  We should adjust the message here when the coupon code is included.  It usually just says...

> We have declined your offer on WooCommerce Demo.

If the coupon code is included, though, we should make it say...

> We have declined your offer on WooCommerce Demo, however, we do have an active coupon code that we can offer you for use on our website.

**Comment by angelleye** [comment]
This is still not working correctly for me on the details page even from the "latest" branch.  I still see the error that the expiration date is passed even though it's not, and when I switch to "Declined" in the drop down I don't see anything come up allowing me to add a coupon code.

**Comment by kcppdevelopers** [comment]
I have resolved above problem/changes and push to issue-23-latest branch.
