### ISSUE TITLE
WPML Compatibility..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#233]
User reporting problems with comment system through WPML after activating the Offers plugin:  https://wordpress.org/support/topic/comment-backend-with-wpml-not-working?replies=2#post-8041037

**Comment by Zwilla** [comment]
to show what I mean video:
https://www.zwilla.de/en/woocommerce-en/no-comments/

**Comment by angelleye** [comment]
Thanks!  We'll get this worked out as quickly as we can.

**Comment by Zwilla** [comment]
After uncomment this, it works atm normal
File:
class-offers-for-woocommerce-admin.php
Line 691
if ( $screen->id == 'edit-comments' )
