### ISSUE TITLE
Make offer based on cart instead of individual product.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#234]
User requesting for the offer to be available at the cart instead of the product level:  
- https://wordpress.org/support/topic/possible-for-cart?replies=2#post-8048157
- https://www.angelleye.com/support/scp/tickets.php?id=736

I think this sounds like an interesting feature to add.  We should probably add settings in the plugin so that people can enable offers at the product level (product detail page like it is now), the cart level (shopping cart page), or both.

Of course, if they make an offer on a full cart we'll need to make sure the notification emails for everything (new offer, counter, etc.) reflect the full cart.

**Comment by angelleye** [comment]
May decide to turn this into a premium extension.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/OFW-67
