### ISSUE TITLE
User Account Based Offer Management

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#235]
Feature request:  https://wordpress.org/support/topic/offers-page-for-user?replies=2#post-8068555

Need to add the ability for users to see their offers the same way they can see their order history if they are signed in to an account on the website.

They should be all submitted offers as well as the current status of each offer, and if any are accepted/countered for them to buy, they should be able to load up the shopping cart with the offer's content and checkout accordingly.

**Comment by kcppdevelopers** [comment]
http://screencast.com/t/UQkfismkiH
