### ISSUE TITLE
Anonymous negotiation.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#239]
We have a user that wants to make the communication between buyers and sellers anonymous.  

They are using their site for 3rd party sellers, and they don't want those sellers to know the direct contact information of the people making offers for fear that they would just make the deal outside the platform.

So we need to add an option in the settings panel where people can enable "Anonymous communication" and if this is enabled, then the emails and everything would still be sent like they are now, but the actual name and contact info for the person making the offer would be hidden from the seller.

**Comment by kcppdevelopers** [comment]
I am little bit confused here.. we are only sending email to admin person not 3rd party sellers right?

Please correct me if I am wrong.

**Comment by angelleye** [comment]
Yes, for this particular task we are simply making the communication with the buyer anonymous.  We will not be doing anything specific with any 3rd party vendor plugin at this time.

So if somebody submits an offer to the site, the email notifications and everything should work like usual, but the actual buyer contact information should be masked when this feature is enabled.

**Comment by angelleye** [comment]
I mentioned to you the other day that you could go ahead and merge issues into dev, but for this one please leave it in its own branch when you're done with it.  We may be making some more adjustments here.

**Comment by angelleye** [comment]
Basically, what the user that requested this is wanting is that the offers would work like normal except that everything but the price would be hidden.

So the offer could still come through, but all the site admin would see is the price.  They wouldn't see the name, email, notes, or anything else that usually comes with an offer, so those fields could essentially be disabled from the offer form when this feature is enabled.

Once a negotiated price is agreed upon and an order is placed then the buyer details would be available like usual, but within the offers everything would be anonymous except for the prices.

**Comment by kcppdevelopers** [comment]
![issue-239](https://cloud.githubusercontent.com/assets/13145461/15206738/02b0c408-183f-11e6-8dbd-d382067ecea4.png)

**Comment by angelleye** [comment]
I've made a small adjustment to the setting description so make sure you pull that.

Also, I see you made some adjustments to the "new offer" script, but don't we need to do the same thing with counter offers, declined, etc?

**Comment by angelleye** [comment]
I think we still have quite a bit more to do here.  When I had the anonymous enabled I submitted an offer, and I don't see the information in the new offer email, but I can still see all of the details in the admin panel on the offer list page...

![image](https://cloud.githubusercontent.com/assets/629241/15228979/5209e3e4-1854-11e6-8521-68e7d3d71dfa.png)

As well as the offer details page...

![image](https://cloud.githubusercontent.com/assets/629241/15228989/63b12058-1854-11e6-83d5-62dbe51e986f.png)

When anonymous is enabled I shouldn't be able to see that anywhere during the offer / counter offer stages.

**Comment by kcppdevelopers** [comment]
It seems you are not using latest update code, I have uploaded latest code on woo.an*******.com please check again for me?

**Comment by angelleye** [comment]
Reopening this because the user is downloading our current dev branch (which from what I can tell should have all your updates in it) but he's still getting the offer note form on the details page, and when he submits a new offer that offer note still shows up in the email notification that is sent.  This needs to be hidden.
