### ISSUE TITLE
Notification emails question..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#241]
When I submit an offer to myself it comes through with multiple email addresses in the "to" box and I'm not sure where those are coming from..??

![image](https://cloud.githubusercontent.com/assets/629241/15228859/dba6e0da-1853-11e6-8e6c-8d80f2c81632.png)

**Comment by kcppdevelopers** [comment]
In New offer Recipient(s) you have set multiple email address.

Please check this [URL](http://woo.angelleye.com/wp-admin/admin.php?page=wc-settings&tab=email&section=wc_new_offer_email) for more information 

[Screenshot](http://screencast.com/t/5y8GrruNPQV)
