### ISSUE TITLE
But with get_product..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#243]
Pablo Escobedo via email reports...

>I had an issue with the "Offers for WooCommerce" plugin. I fixed it but I'm entirely too lazy to log in to github and go through with a pull request and everything and I'm at work so I figured I would just shoot you a quick message: Around line 809 of offers-for-woocommerce/public/class-offers-for-woocommerce.php you can have a fatal error if get_product returns its default "false" value. I think this ~may~ be related to static home pages but I digress:

>if (function_exists('get_product')) {
$product = get_product($post->ID);
if ($product->is_type('variable') && is_single()) {
$is_product_type_variable = 'true';
}
}

>I fixed it by ensuring $product isn't a boolean before trying to manipulate it further:

>if (function_exists('get_product')) {
$product = get_product($post->ID);
if (is_bool($product) === false) {
if ($product->is_type('variable') && is_single()) {
$is_product_type_variable = \'true\';
}
}
}

**Comment by kcppdevelopers** [comment]
we have already resolved this issue in #242, latest code available in dev branch.

Please see the [code ](https://github.com/angelleye/offers-for-woocommerce/commit/299604dd354872e8ee0f7c40aafe3e17a609aa7a#diff-13a4758c714adedb093dc77327b15a1cR810)different.
