### ISSUE TITLE
Option to show offer button for affiliate/external products.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#247]
In #24 we hid the offer button for affiliate/external products.  Since there was no add to cart button on these, and people leave the site to make their purchase, it didn't seem to make sense to include an offer button.

We are getting requests, though, to make an option to show the offer button.  People like domain name resellers who redirect people to a 3rd party to make the purchase, but would still like the feature where people could send them an offer directly.

So we need to add an option in the settings for the plugin that lets you "Enable offers for external products."

**Comment by angelleye** [comment]
Pushing this to a later version because it's going to require adjusting email notifications as well as the admin management screens for offers related to external products.  Don't want to spend that much time on this now because this isn't a high priority item.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/OFW-66
