### ISSUE TITLE
Better error handling when product no longer exists.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#251]
https://wordpress.org/support/topic/call-to-a-member-function-get_permalink-on-a-non-object?replies=7#post-8797244

https://www.angelleye.com/support/scp/tickets.php?id=760

**Comment by keyurptl** [comment]
can't reproduce this issue. i follows steps as per give [ticket ](https://wordpress.org/support/topic/call-to-a-member-function-get_permalink-on-a-non-object?replies=7#post-8797244) 
i can throw exception based on fatal error, but that is just hunch not a proper solution.

**Comment by angelleye** [comment]
Seems the notification we have added is only on the buyer side, when looking at their offer history in their account page.

We also need to include a message to the admin to manage this better.

If an admin is deleting a product that has a pending offer, we should display a notification:  "There are current offer(s) pending on this product.  How would you like to proceed?"

Then we can provide options:

1. Decline pending offer and continue deleting product.   (this would trigger a declined offer just like any other declined offer, so the buyer would be notified accordingly.)
2. Accept the offer and do NOT delete the product.  (this would trigger the accepted offer like any other.)

**Comment by angelleye** [comment]
As discussed previously, by following the steps outlined above, the changes you made in the previous commit would become obsolete.

**Comment by angelleye** [comment]
@keyurptl Catch on on Skype when you're back please.  I'd like to discuss this one before I merge it.

**Comment by angelleye** [comment]
Reading what I said above...I don't think that will be so simple.  If a product has multiple offers pending then it would require more work to manage it correctly.  We can simplify this so that we follow this procedure...

If the site admin attempts to delete a product that has pending offers, display a notice that says...

"There are pending offers for this product.  Would you like to decline all pending offers and continue deleting the product?"

Then they would have a simple OK / Cancel option on the dialog.

**Comment by angelleye** [comment]
We wound up simplifying this so that there is no option for anything.  If you delete a product that has related offer records, it's going to automatically delete all open offer records for that product as well.
