### ISSUE TITLE
WooCommerce Variations to Table Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#252]
https://wordpress.org/support/topic/offer-button-doesnt-work-with-woocommerce-product-variations?replies=10#post-8797266

**Comment by angelleye** [comment]
@tejasm-itpath I'm getting a small merge conflict on this when attempting to merge into the dev branch.

Please switch to your Issue-252 branch and then merge the dev branch into that, which should result in the same conflict so that you can resolve it in the Issue-252 branch.

**Comment by tejasm-itpath** [comment]
Merged dev in to Issue252 with this commit
https://github.com/angelleye/offers-for-woocommerce/commit/65eea84257d60a0259b35316fa8bb8579376ae4b
