### ISSUE TITLE
Errors submitting offers from mobile browsers..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#255]
Szabolcs Szekely via email reports...

> I recently installed Offers for WooCommerce Plugin and I get
> an error message when the shopper tries to make an offer for a product via Mobile version of my site (tested in Android, chrome)..
> 
> Error: There was an error sending your offer, please try again. If this problem persists, please contact us.
> 
> However I still do receive the offer on my administration back end.
> 
> If offers are made from a desktop there is no error, only at mobiles.
> 
> I'm using the latest Wordpress, and Zerif Pro theme. I've disabled all the plugins and also switched for Twenty Sixteen theme for a test and I still get the same error when the offer is paced from android chrome.
> 
> http://sendvid.com/jdoee6dq

**Comment by keyurptl** [comment]
http://screencast.com/t/z7HMgTHz1Y
i have tested site on [chrome remote debugg](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3#enable_usb_debugging_on_your_android_device) and not found any issue.
Tested Device : MOTO G2, MICROMAX Q381

**Comment by angelleye** [comment]
I've emailed this user to ask if they are still having troubles with it, and provide more details about how to reproduce.

**Comment by angelleye** [comment]
>Thanks for your reply Andrew, 
Yes the problem is still persists I was using the latest Safari on a Macbook. The offer goes through, but it spits out that error and leads you to believe it doesn't go through. Not sure about all other browsers, however the error is on in chrome on android phones too. 

>I've enabled offers on the following product: you can test it if you need to: https://dot50.com/affordable-domains/virtudor

**Comment by angelleye** [comment]
@keyurptl Catch me on Skype when you're back.  I'd like to discuss this one.  

The commit for this issue (255) shows only a single file changed with 3 additions and 13 deletions, so that's what I expect to see when I pull the changes.

When I pulled this issue branch, though, it pulled 6 files with 250+ changes.

That means this issue branch has things you've done in other issues already merged into it, which means that I cannot easily test ONLY the commit that is related to this issue.

I think I may know how this happened.  I think you're still creating your issue branches from your dev_itpath branch instead of my dev branch.

So in this case you worked on 251 in the Issue-251-B branch, which you then merged into your dev_itpath branch.

Then you started working on #251, and you created the Issue-255-B branch from your dev_itpath branch, which already had Issue-251-B merged into it.

This results in the Issue-255-B branch including everything you did in Issue-251-B as well as what you did in Issue-255-B.

Instead, you should have created Issue-255-B from the dev branch, and then the changes in Issue-255-B would be nothing but those commits, which is what I like.

You can continue merging each individual issue branch you do into your dev_itpath branch so that it's always up-to-date everything you've done, but again, you need to make sure you're creating new issue branches off of "dev" instead of "dev_itpath".  

In cases where two or more issues depend on each other you'll be able to work from your dev_itpath branch without any issue.  In those cases, please leave notes in the related issues about how they depend on each other, and I'll be able to pull changes in order so everything works as expected as I go through review.

Please let me know if you have any questions or concerns about anything I've mentioned above.

**Comment by mdrahul** [comment]
I have tried to reproduce the same issue from Chrome in Android Mobile and Safari(10.0.1) on Mac(10.12.1). I have tried to reproduce the issue for logged in and non-logged in users with offer form in lightbox and tabs and it is working fine for all the cases.

Please let me know if you have any questions or concerns here.
