### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by R-K-Shrivastaw** [angelleye/offers-for-woocommerce#256]
Hi...
Greeting of the Day !!

Today i installed your make an offer plugin in my wordpres 4.2.2 with Woocommerce 2.6.1 
but i got a fatal error

**Comment by angelleye** [comment]
I'll need to know the actual error to try and help, but I'm assuming it's probably a conflict with the WordPress version.  They're up to 4.6.1 now and have made quite a few changes with functions since 4.2.2.  I would recommend you update WordPress and see if the problem continues.

**Comment by R-K-Shrivastaw** [comment]
conflicting error is fatal error - idex-.php - line no 28

**Comment by angelleye** [comment]
Yeah, you're going to need to get updated to resolve that issue.
