### ISSUE TITLE
Ability to display highest current offer on the front end / product page.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#257]
Steve Anders via email:

> After a user has made on offer on a product they want the ability to display the current highest offer on the product page. I have found the setting to display how many offers a product has, but I do not see an option to display the amounts offered. Does this functionality exist? Is there potentially a code work around that will display this value?
- We need only the highest offer to display on the front end product display page.
- If there are multiple offers of the same amount we need the most recent to display.
- We need a shortcode call so that we can move the position of the displayed offer.

**Comment by angelleye** [comment]
So I think what we can do here is add an option in the settings panel where you can "Display highest current bid on product page."

If this is enabled, it would display that nicely on the product page next to the product price.

The shortcode we can make available regardless of whether it's enabled on the product page.

**Comment by angelleye** [comment]
I've made some adjustments to verbiage.  I'm also trying to use number_format($max_amount,2) so that it will output 2 decimal places, but for some reason it's not working for me..??

For example, this...

![image](https://cloud.githubusercontent.com/assets/629241/19230778/edc9bd32-8e9b-11e6-9678-152a06019f22.png)

Needs to be 10.00 instead of just 10.

**Comment by kcppdevelopers** [comment]
I am done with price format and shortcode functionality and push to the issue branch.

Below is the shortcode example.
> [highest_current_offer]

**Comment by angelleye** [comment]
Re-opening this because the Highest Current Offer box is getting output on the product page even when offers are not enabled for the product.  To reproduce...

1. Enable offers for a product.
2. Submit an offer for the product.
3. Refresh the product page to see the Highest Current Offer displayed.
4. Disable offers for the product.
5. Refresh the product page and you'll see the offer button goes away, but the Highest Current Offer still displays.  We need to make sure we are only displaying this if offers are enabled for the product.

**Comment by angelleye** [comment]
One more thing I'd like to do here.  The Highest Current Offer div we added is showing up under the product price.  Then our offer button and pending offer count shows up after the add to cart button...

![image](https://cloud.githubusercontent.com/assets/629241/21452453/9a4c1f7c-c8cc-11e6-84c0-36c1c8ce055f.png)

I would like to move the Highest Current Offer div so that it shows up after the offer button, before the pending offer count.

**Comment by angelleye** [comment]
@mdrahul 

This is working fine for me on products with a price...

![image](https://cloud.githubusercontent.com/assets/629241/21497658/305f4238-cbec-11e6-9611-5e44eac40313.png)

However, on products without a price the Highest Current Offer box is not showing up at all.

![image](https://cloud.githubusercontent.com/assets/629241/21497688/61574b24-cbec-11e6-9542-1f78bcb04b30.png)
