### ISSUE TITLE
Call to undefined function get_current_screen()

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#258]
https://wordpress.org/support/topic/php-error-infinitewp

**Comment by keyurptl** [comment]
IWP(1.6.1.1) plugin is not support WP version 4.6.1(latest) so can't reproduce issue.

**Comment by angelleye** [comment]
We can address this again in 1.4.0 and see if they've updated by then.  The update alone may solve the problem.

**Comment by angelleye** [comment]
IWP 1.6.3.2 is their current release and is now compatible with WP 4.7.  Let's go ahead and see if we can reproduce this problem now, or maybe they got it fixed with their own updates..??

**Comment by mdrahul** [comment]
I am not able to reproduce this problem in the latest version of plugin and WP. Please let me know the WordPress and plugin version so that I can reproduce this issue.

**Comment by angelleye** [comment]
Ok, if it's not a problem on the latest versions of things we won't worry about it.
