### ISSUE TITLE
Consider Inventory

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#26]
Need to make sure the system is checking that inventory is available to complete the order when the following events occur:

* New offer is made (just like add to cart would validate inventory if enabled in WC options)
* Offer status is updated
  * Pending offer status updated to accepted/countered.

**Comment by kcwebmedia** [comment]
**What we need is -- Show admin error msg/notice if the offer exceeds stock available.**
* If stock management ON for the product, and back orders not allowed, and stock amount available is less than offer qty, then WARN the admin about it.
 * Show warning message html/css ON page load
 * Show warning message with jquery dynamically ON post_status input change()
 * **Still allow the offer to be accepted/countered even if exceeding stock**

NOTE: The Offer Summary panel on offer detail already is displaying 'stock' OR a red 'out of stock' msg if back orders not allowed, etc.
