### ISSUE TITLE
Additional option for "only logged in users" setting.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#263]
We currently have an option where you can choose to only allow offers for logged in users.  If this option is enabled the offer button and everything is completely hidden.

We have a [user requesting an adjustment to this](https://www.angelleye.com/support/scp/tickets.php?id=835).

What they would like is that when the option to allow offers for only logged in users is enabled, still show the offer button so people can at least see that option would exist, but when they click on it force them to login / create an account prior to displaying the offer form and allowing them to submit the offer.

**Comment by angelleye** [comment]
We're still missing some steps here.

Everything seems to be working with requiring the log in and then allowing me to submit the offer after I log in, which is good.  However, if I do not already  have an account there is no place for me to easily create one as part of this process.

I see that it's just using the "my account" page to handle the login..??  We need to somehow add a "Create Account" option to this login screen, or at least add a link to another page where they can create the account, or whatever provides the best flow at this point.

We also need to make sure that the offer URL reference remains in tact so that after the account is created the user can be dropped into the product page / offer form.

**Comment by mdrahul** [comment]
If there is registration enabled for my account page from admin side then it will display registration form also in the account page. So if the user creates his account from here then this functionality will also work. You can do it from admin by going to WooCommerce->settings->account and tick the checkbox - Enable registration on the "My Account" page.

Also offer URL reference remains same when the user successfully registered from here.

**Comment by angelleye** [comment]
@mdrahul I am running into a small merge conflict when I merge Issue#263 into dev.

Please fix this for me by switching to the Issue#263 branch and then merging dev into that.  This will result in the merge conflict, so then you can resolve it directly in Issue#263 branch.

**Comment by mdrahul** [comment]
I have fixed merge conflicts. Please review it.
