### ISSUE TITLE
Hooks for Premium Extensions

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#265]
We have plans of building extensions for WC Vendors Compatibility, Dokan Vendors Compatibility, etc.

We need to try to think of all the hooks we'll need from this plugin so that we can easily extend the functionality from our premium plugins.

**Comment by angelleye** [comment]
@mdrahul Any other hooks you can think of that we may need for future plugin extension development?  We may as well go ahead and get them added now.

**Comment by mdrahul** [comment]
I am looking into whole code of plugin and if I find any place where we can provide hook/filter then I will add it and then I will update here.

**Comment by mdrahul** [comment]
We have following new hooks:

1. ofwc_before_offer_button_output
2. ofwc_after_offer_button_output
3. woocommerce_before_offer_submit

Following new filters:
1. ofwc_offer_button_output

@angelleye We need to address this in our plugin documents also.
