### ISSUE TITLE
Improvements in error handling when product no longer exists or deleted from admin.

### ISSUE THREAD

**Issue by mdrahul** [angelleye/offers-for-woocommerce#266]
In #251 we deleted any open offer records when products are deleted.  We don't have any sort of notification when this happens, though, so I'd like to add something that lets the user know there are existing offers they may want to review prior to deleting the product.

So we could simply add a single notification...

"There are current offers pending for this product.  If you continue the offer history will be deleted along with the product."

And then they would have an OK / Cancel button.

**Comment by tejasm-itpath** [comment]
We have added Offers column in the product list in wooCommerce and highlighted as bold font so that user can see it before product delete.
