### ISSUE TITLE
Adjust method for hiding offer buttons to follow WP standards.

### ISSUE THREAD

**Issue by mdrahul** [angelleye/offers-for-woocommerce#267]
Hi Andrew,

I have found that some of the code can be reused using creating functions. One thing is that there is only after add to cart hook is used to display the make offer button. For all other positions like before add to cart, after price and all there is Jquery code written which is copying the HTML code of button from after add to cart hook and then appending it to the other positions. Please review the code from your side and let me know your thoughts on that.

I have shared video regarding this at https://drive.google.com/file/d/0BzDiIbD5BsmcQURxV0dnM2NHZms/view?usp=sharing.

**Comment by angelleye** [comment]
Okay, go ahead and make the adjustments you feel are necessary here based on what you've shown me.

**Comment by mdrahul** [comment]
We have made adjustments for hiding/showing offer buttons. We have managed this changes in issue #273  . So now I think we can close this issue.
