### ISSUE TITLE
Process Paid Orders from Offers

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#27]
Build functions to process order/offer data when an order from an offer has been paid.

We'll have to discuss this more. Our original thought was that we would update the offer status to "completed" or "paid" when the order was paid, but that should happen already based on the relationship.  So the offer status would remain "Accepted" and the order status would be "processing" or "completed" or whatever.

Since we have the offer ID in the order meta data, we can simply display the order status in the offer views using the relationship (sql joins). If there is no order, nothing would be displayed, but as soon as an order is created from an accepted/countered offer, then the offer view would show "pending", and when it was updated to anything else it would always reflect based on the relationship.

Just need to also consider anything else we may want to automate based on when an order from an offer is paid.

**Comment by kcwebmedia** [comment]
**We need to use Woocommerce HOOK: 'woocommerce_order_status_completed'**
* If 'completed' order -- set Offer post_status == 'completed-offer'

**Offer Details - Need to lookup order(s) that have this offer ID in the order meta**
* List related 'Orders' - include order ID, status, order date, link to order

**Comment by kcwebmedia** [comment]
If Order is marked as 'cancelled' or 'refunded', and it relates to an offer that is currently 'completed-offer', then the offer needs to be updated back to either 'accepted' or 'countered'.
* This will allow customer to process a new order on the same approved offer

Hooks REF:
* woocommerce_order_status_cancelled
* woocommerce_order_status_refunded
