### ISSUE TITLE
Flatsome Theme Conflict

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#270]
* https://wordpress.org/support/topic/add-to-basket-button-shows-up-on-product-listing-page/
* https://www.angelleye.com/support/scp/tickets.php?id=872

User reports that the Flatsome theme has an option to hide the add to cart button on home page / shop pages, but when Offers for WooCommerce is enabled the add to cart button shows up on those pages even when the theme has it disabled.

The user double checked that our option to show the offer button on home / shop pages is NOT enabled, and the offer button is indeed not showing up, however, our plugin is somehow overriding the theme's option to hide the add to cart button and causing it to be displayed when it shouldn't.

I've asked the user to provide the theme so we can test it out locally.

**Comment by mdrahul** [comment]
This issue is generated due to the fixes we have made in Issue #251. So if we fix this then it will affect the Issue #251. So better if users want to remove add to cart button from shop page then they should hide it using CSS and not by using the filter/hook you have used in functions.php of the child theme. 

You can put following CSS into style.css of active theme to hide add to cart button from shop page:
.archive.woocommerce  a.button.add_to_cart_button {display: none;}

**Comment by angelleye** [comment]
@mdrahul I'm confused, what does the error handling when a product has been deleted have to do with the add to cart button getting displayed on the front-end when it shouldn't be?

**Comment by mdrahul** [comment]
I have updated my previous comment. Please review it.

**Comment by angelleye** [comment]
My question still remains.  How does the blank price issue relate to this?  Whatever we did there shouldn't be breaking CSS for people where it wasn't broken before.

**Comment by mdrahul** [comment]
This is the issue about not to displaying add to cart button on shop page and not about CSS right? 

Actually, We have enabled is_purchasable() for blank price products which will display cart button for products with blank price which is not valid in Woocommerce, so we have used hook to remove the add to cart button for them and we are adding add to cart button for other products as it is in loop for shop page which overwrites client's hook to hide add to cart button.

**Comment by angelleye** [comment]
Sorry, yes, I was confusing a different issue with this one.

We'll need to discuss this more when we're both online.  I don't fully  understand why we're hiding a button just to force it to be displayed again after that.  

One way or another we'll need to address this.  We can't have our plugin overriding theme settings.

**Comment by Cyb3rWaste** [comment]
Same issue on X theme. Can hide on shop pages with CSS but any place that uses a shortcode to display products has the unwanted button.

**Comment by angelleye** [comment]
@mdrahul We still need to address this again.

**Comment by mdrahul** [comment]
We have fixed this issue using CSS and Jquery instead of using a hook. So now there is no need to change in core files of the plugin for your site.
