### ISSUE TITLE
Shipping Cost Option Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#271]
In #216 we added the ability to set a shipping cost on the offer.  From the offer manage screen you can set a cost, and then that cost would be added as the shipping price during checkout for the offer.

The following things need to be addressed here:

1. The default shipping title for the offer shipping rule has a typo:  "Offer Shiipng Cost" needs to be fixed (*** already did this in the commit below ***).

2. When the offer first comes in our "shipping cost" on the manage offer screen defaults to 0.00.  That implies the shipping should be 0.00 when the buyer checks out.  It's not, though.  If shipping is not > 0, then the site just falls to the regular shipping calculators that are configured.  

This could also cause confusion for the site owner / offer manager, because they might think they're supposed to calculate shipping on their end when accepting the offer or the buyer would get it free. 

I think the best way to handle this would be to add a check box on the offer manager screen next to the shipping cost, so you have to "Include shipping with offer."

If this is checked, then you can enter the shipping amount, which still defaults to 0.00, but could be set to anything you want.

If left at 0.00, then the buyer should indeed get the 0.00 shipping forced just like it would an actual amount.  If an amount is set, of course, it would act like it does now and apply it.

**Comment by angelleye** [comment]
@mdrahul Our new option we added says "Enable Shipping Cost".  I'd like to change this to say "Include Shipping with Offer".

**Comment by angelleye** [comment]
@mdrahul In the new option we have...

![image](https://cloud.githubusercontent.com/assets/629241/23201771/b6f20eee-f8a0-11e6-9a2c-2c9a7c4ce350.png)

The "Include Shipping with Offer" checkbox and label are sort of crammed into that space between the Price Per and Total fields.  Can we add some padding / margin so that it separates that a little bit and looks a little cleaner?

**Comment by mdrahul** [comment]
I have applied the fix for the spacing you have mentioned in the last screenshot. Please review it and let me know if you find any queries.
