### ISSUE TITLE
Browser conflict w/ potential solution..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#272]
* https://wordpress.org/support/topic/getting-there-was-an-error-sending-your-offer/page/2/#post-8671558

**Comment by mdrahul** [comment]
I am not able to regenerate the issue. Can you please let me know the steps to regenerate the same thing so that I can look more into that?

**Comment by angelleye** [comment]
Unable to get a response from the original user that reported this, so we're closing it out.
