### ISSUE TITLE
Double Email Headers Review

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#275]
In #227 we made some adjustments to fix double email headers.  We are getting feedback from a user saying these adjustments are causing problems.  

>I'm using your plugin in the current version and also the PDF Invoices and Packing Slips Plugin in Version 1.5.38. Both plugins activated the headers and footers from all emails are gone - except, interesstingly, the emails form the offers plugin (Offer received, Counter Offer, etc.), which still have header/footer.

>What I tried so far:

>Turning off one of both plugins: Headers/Footers are back again.

>Removing [this fix](https://github.com/angelleye/offers-for-woocommerce/commit/bd224e8298fcbddff1ac68560d852b36e95718f4) regarding this problem, file: public/class-offers-for-woocommerce.php, lines 178-181: Headers/Footers are back - and also not duplicated like in the orginial issue here.

**Comment by chrwald** [comment]
If I can help you guys testing or antyhing, just send me a short note. Thank you for looking into this.
