### ISSUE TITLE
Customer Offer History

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#28]
When a user is logged in to the site and submits an offer we can store the customer ID in the offer meta data so that it relates back to the customer record.

Then we can build an "offer history" screen in the customer profile.

**Comment by kcwebmedia** [comment]
* IF logged in user, New Offer OR New Counter Offer, store WP user's ID as 'author' on the POST. This will allow us to filter by ?author GET var later.

* Add Query 'Total Offers COUNT' prior to loading 'manage offer' screen

* Add 'Buyer Offer History' panel within Offer Details panel on 'manage woocommerce offer'
 * Show 'Total Offers COUNT'
  * IF count, THEN show 'view history' link
    * Link to offers edit list, filtered by specific user ( /?author=XXX&post_type=woocommerce_offer... )

* IF on offers list screen, AND has /?author GET var, THEN add WP notice - 'filtered by author...'

**Comment by kcwebmedia** [comment]
* IF not logged in, check if email matches known wp user
 * IF match, THEN set post_author (On NEW or COUNTER posts)

**Comment by kcwebmedia** [comment]
* Relabel the buyer's offer history to real "Buyer Offer History" (2 spots) so that it doesn't get confused with the Offer's history/counters.
