### ISSUE TITLE
Provide link in admin bar to go to pending offers directly from product details page in front side.

### ISSUE THREAD

**Issue by mdrahul** [angelleye/offers-for-woocommerce#280]
We need to add manage offers option in admin bar so that admin can directly go to the offers in admin side where we will display all offers in meta box for each product.

**Comment by mdrahul** [comment]
I have made related changes in our issue #277. Please review it.

**Comment by angelleye** [comment]
@mdrahul We need to format the numbers to clean this up and make it more presentable:

![image](https://cloud.githubusercontent.com/assets/629241/23357648/61af5088-fca4-11e6-97d6-6fc3570c6277.png)

Make sure the Price Per and Amount are formatted with 2 decimal places and the currency symbol.  Of course, make sure the currency symbol matches the currency set in WooCommerce.

**Comment by angelleye** [comment]
@mdrahul Can we make the column headers clickable / sortable?

Also, please center align the Quantity column.
