### ISSUE TITLE
Payment canceled in Paymentgateway site

### ISSUE THREAD

**Issue by JanKrol** [angelleye/offers-for-woocommerce#281]
Hello,

I have an improvement for this awesome plugin. When the user cancels the payment in the payment gateway site, the offer gets the status "completed" which is not true. I just inserted a simple if check before changing the status for the offer BUT the method has to be fired at the thank you site because the database is not yet finished at `'woocommerce_checkout_order_processed'`.

In  offers-for-woocommerce/public/class-offers-for-woocommerce.php
line 140:

`      add_action('woocommerce_thankyou', array($this, 'ae_ofwc_woocommerce_checkout_order_processed'));`

and the appropriate method:
```
public function ae_ofwc_woocommerce_checkout_order_processed($order_id) {
        global $woocommerce;

        // Get Order
        $order = new WC_Order($order_id);
        // Get order items
        $order_items = $order->get_items();

		//check if order really wc-completed and not aborted!  <------- this is NEWWW
		if ( get_post_status( $order_id ) == 'wc-completed'  ) {
        // Check for offer id
        foreach ($order_items as $key => $value) {
            $item_offer_id = $order->get_item_meta($key, 'Offer ID', true);
        //and so on
```

**Comment by angelleye** [comment]
@JanKrol Thanks for the feedback!  In the future you could submit a pull request, but we'll just take a look at this and implement it accordingly.  

@mdrahul Please review this to confirm you're able to reproduce the problem and then implement the fix accordingly.

**Comment by JanKrol** [comment]
Alright: Think also to change 

`add_action('woocommerce_thankyou', array($this, 'ae_ofwc_woocommerce_checkout_order_processed')); `

in the same php file.

Best regards 

Jan

**Comment by mdrahul** [comment]
@JanKrol Thanks for the note. I have made changes for this.

**Comment by angelleye** [comment]
@mdrahul After applying this update I ran a test order where I fully completed the checkout.  The offer status was left as accepted instead of updating to completed, so it seems that what we've done here isn't quite correct..??

**Comment by angelleye** [comment]
@JanKrol FYI, we're releasing another update soon that switches this to the order_status_completed hook instead of using the thankyou hook.  

This is because some payment gateways (ie. PayPal Standard, Adaptive Payments) can be completed even though the user does not make it back to the thank you page.

In these cases PayPal IPN is typically  used to update the WC order status, but our offer status was not getting updated in this case.  Switching to the different hook will ensure the offer status gets updated when the order status does.
