### ISSUE TITLE
We need to remove the edit product link if the vendors are not allowed to edit the live products

### ISSUE THREAD

**Issue by mdrahul** [angelleye/offers-for-woocommerce#284]

**Comment by angelleye** [comment]
Only in cases where WC Vendors is being used, of course.  It might make sense to create a function like isMultiVendor() that checks for WC Vendors, and can be used to add other checks as we add additional multi-vendor products in the future.

**Comment by mdrahul** [comment]
We have already created one function to check if the user is the vendor for our extension. The function's name is : "aeofwc_is_vendor()". So you mean we need to create the same function in our main plugin?
