### ISSUE TITLE
Recaptcha Conflict with 3rd party plugins / themes..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#290]
* https://wordpress.org/support/topic/conflict-when-using-other-plugins-with-recaptcha/

**Comment by tejasm-itpath** [comment]
http://stackoverflow.com/questions/43370449/errors-due-to-duplicate-js-files-in-wordpress-page
Asked Question in Stackoverflow as I can't figure out the solutions

**Comment by angelleye** [comment]
@tejasm-itpath I see you never got a response to the SO ticket.  Do you have any other ideas about how to get this fixed?  Seems like there should be a way to check for existing recaptcha JS to make sure only one gets used..??

Also, I'm a little confused how GravityForms is conflicting with our form..?  Is there a separate gravity form on the same page as our offer form?

**Comment by tejasm-itpath** [comment]
@angelleye 
I have added gravity form with captcha in the description of the product and Make offer form with captcha , So when there are two re-captcha found on same page , it cause issue.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/OFW-62
