### ISSUE TITLE
Offer enable/disable bug with items on sale..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#293]
* https://mail.google.com/mail/u/0/#inbox/15af7cdd8381616e

>Hi Guys, I seem to have a glitch in the Offers for Woocommerce Plugin. When selected in certain selected items it works fine but if I have a sale price & deselect all the option to have an Offer active on said item the text stays but the background button disappears & is still an active link. So basically, even if Offers is deselected in the options it is still visual on an item I have on "Sale" only. If the items aren't on Sale then the "Offer" doesn't appear on the product. Any solutions to this issue? Cheers Rob

**Comment by angelleye** [comment]
>* When the “After Product Tab” is selected in the settings it doesn’t display the “Offer” button at all.
>* & as I mentioned previous when you have deselected all the options the text stays there on the item for sale, but if you take the item off Sale then put it back on Sale the “Offer” Button doesn’t reappear.
>* Then if you simply open the “option” in the product with nothing selected & not selecting any option it reappears back in the item.

**Comment by angelleye** [comment]
>Hi Andrew, I have tracked it down to one of the setting selections in Offers for Woocommerce – Settings, If you uncheck the option “Show On Shop Page” it takes the Offer text off all Sale items.

**Comment by tejasm-itpath** [comment]
Can't Get it exactly, Need to understand practically. @angelleye

**Comment by angelleye** [comment]
@tejasm-itpath Do you have any specific questions about this?  The quoted notes seem pretty straight forward.  Did you test sale items the way he mentioned?

**Comment by tejasm-itpath** [comment]
@angelleye  I am not getting which options he deselected ?
What is not displaying when deselected ?
Honestly I am not getting flow
