### ISSUE TITLE
CSS Class Name Adjustment Necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#295]
* https://www.angelleye.com/support/scp/tickets.php?id=1012

In #286 we added a CSS class name option to our settings, but it seems people are having trouble using it because we still have inline CSS with !important on it..??

>I added a custom CSS Class name "make-offer" but still had issues adding a green border to the button... seems that your inline style with !important is too strong and i cannot overright. here is my CSS:

```
body button#offers-for-woocommerce-make-offer-button-id-487.make-offer {
border: 1px solid #b2d91f; !important
border-color: #b2d91f !important;
```

**Comment by tejasm-itpath** [comment]
https://github.com/angelleye/offers-for-woocommerce/commit/66f89f5cdee315edc4e9d525343286465485c6b0
