### ISSUE TITLE
WC 3.0 compatibility

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/offers-for-woocommerce#296]
* https://www.angelleye.com/support/scp/tickets.php?id=1043

After Major updates of WC ,  Offers For woo-commerce Plugin giving error message 

> Sorry, this product is unavailable. Please choose a different product.

Issues are
1)  WC have removed hidden field from where we are fetching product post id.
2) autonumeric js error
3) Offers are not inserting into the database.

**Comment by angelleye** [comment]
@tejasm-itpath Is this ready?

**Comment by tejasm-itpath** [comment]
@angelleye 
Yes .. I have found 2 issue on this and may be i can find more issue that's why i haven't added label Ready for review.
