### ISSUE TITLE
Product Variations Compatibility Improvement..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#299]
In #252 we added support for product variations.  The immediate feedback we got is this:

>I would like to make a suggestion. I use the pop up for the make offer. Could you please make it where they can choose the variation in the pop up after clicking the make offer button. Thanks

Let's go ahead and make that improvement if we can.

**Comment by angelleye** [comment]
We now have a report that variations are not working at all:  https://www.angelleye.com/support/scp/tickets.php?id=1159

**Comment by tejasm-itpath** [comment]
@angelleye 
About product variation ,we have to take care of the Woo variations table plugin compatibility.
According to this issue , it's better to display just Label of the selected option/ Selected criteria and price
so user have idea about product while making offer.
what's your thoughts about it ?

**Comment by holkakhol** [comment]
That would be really good, because right now i'm stucked with variations. Offer links only to parent products..

**Comment by tejasm-itpath** [comment]
@angelleye 
This is covered in #328
