### ISSUE TITLE
WC 3.0 compatibility adjustments

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/offers-for-woocommerce#301]
@tejasmht 
for front-end = https://www.diigo.com/item/image/60eoh/bmy4
Case : After activation of plugin on a new site if i go to my shop page and click on any product to see detail / single page, I am seeing following notice which I think should not be there and these should be managed properly.

For backend https://drive.google.com/file/d/0B1qByE9I9z9yOUhOT3JuMmNpZzA/view?usp=drivesdk

Case: on backend woocommerce > offer > click on manage offers to see any offers detail page and you will experience above mentioned notices

**Comment by tejasm-itpath** [comment]
@angelleye  
I have tested this commit with **2 Wordpress setup.**

1) **WooCommerce version 3.0.4**  and **offers-for-woocommerce issue 301**
2) **WooCommerce version 2.6.4**  and **offers-for-woocommerce issue 301**

**Comment by MansoorAliKhanOfficial** [comment]
@tejasm-itpath 

Thanks for the updates I have tested and it seems like working,

Thanks

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial This issue should not have been closed yet because the changes were not yet merged into the dev/release branch.  When new things like this are completed I typically review the changes, merge the code, and close the issue myself.
