### ISSUE TITLE
Safari browser failing to submit offer..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#303]
* https://mail.google.com/mail/u/0/#inbox/15b222904afa0106

**Comment by tejasm-itpath** [comment]
Hi @angelleye 
I have tested this in **Safari Version 10.0 (12602.1.50.0.10)**  In i-os PC.
Also tested in Safari Browser For Windows.
It works perfect.

**Comment by angelleye** [comment]
@tejasm-itpath Okay, I will check with the user that reported this and see what version they're running.

**Comment by tejasm-itpath** [comment]
@angelleye Okay thanks.

**Comment by tejasm-itpath** [comment]
@angelleye Okay thanks.

**Comment by angelleye** [comment]
Another user reporting the same issue with Safari.

**Comment by tejasm-itpath** [comment]
@angelleye 
I have tested this issue in safari and firefox of iMac and Macbook Pro, we still can't reproduce in our system, Also tried test offer in https://www.ztijl.com/ url (Client's URL) and it giving success response.

**Comment by angelleye** [comment]
@tejasm-itpath Did you test Safari 10.0.3 specifically?

**Comment by tejasm-itpath** [comment]
@angelleye  Yes

**Comment by angelleye** [comment]
Responded back to WP support thread in hopes for more details on how to reproduce this.
