### ISSUE TITLE
BT Internet - Michael Buxton - Custom Project

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/offers-for-woocommerce#307]

**Comment by tejasm-itpath** [comment]
@angelleye 
Here is the template file, you can rename it as .php extension.
[woocommerce-new-offer.txt](https://github.com/angelleye/offers-for-woocommerce/files/972940/woocommerce-new-offer.txt)

**Comment by angelleye** [comment]
From the customer...

> I would like to include 'File No' which is a custom field that I store against the product using Advanced Custom Fields. How can I do this?

We just need to get this added into the Admin email notification that he gets when a new order takes place.  Let's include good comments in the template file guiding him on how to add additional fields in the future.

I would also like to write up a very basic list of steps to create custom templates and add fields to other WC email notifications.

**Comment by tejasm-itpath** [comment]
@angelleye
This is how we placed FileNo in the Product table 
https://www.screencast.com/t/aCKtsFnn

**Comment by tejasm-itpath** [comment]
**Steps For this custom templets**
1) we are receiving  Offers array from the **$offer_args** variable.
2) That variable is defined in the **WC_New_Offer_Email** class.
3) That class includes  _init_form_fields_ method that contains array of the fields and we can add fields in that method.
4) Whatever fields we set in the method are used for the custom emails templetes.
