### ISSUE TITLE
Offers for WooCommerce WC Vendor Compatibility

### ISSUE THREAD

**Issue by hendcorp** [angelleye/offers-for-woocommerce#308]
Hi @angelleye ..
I'm using your Offers for WooCommerce – WC Vendors plugin and I found an issue when editing an offer from the WC Vendor front end dashboard. This issue only appears when I set the Offers Status into 'Declined'. After click Submit button, it get stuck.

After searching the culprit, I found that you put `exit;` on line 50 inside **offers-for-woocommerce/admin/includes/emails/woocommerce-offer-declined.php**

I remove it and it works. Is it normal? I'm wondering why you put `exit;` on that email template?

**Comment by angelleye** [comment]
@hendcorp Thanks for the feedback.  We'll look into this and make necessary adjustments in the next update.

**Comment by tejasm-itpath** [comment]
Hi @angelleye  I have resolve this issue in #276 while email template adjustments.
You can check it woocommerce-offer-declined.php line number 50-51 at this commit https://github.com/angelleye/offers-for-woocommerce/commit/1122e211e8052b9916d9a0e6e34a3e9c9767af81.
Thanks

**Comment by angelleye** [comment]
@hendcorp This has been resolved and will be included in the 1.4.7 update we'll be releasing soon.
