### ISSUE TITLE
WC Vendors Pro compatibility issue with post type

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/offers-for-woocommerce#309]
https://www.evernote.com/shard/s39/sh/738a5263-c1e9-431c-9e5e-5dd61995fdaf/061547e2ff392aac

**Comment by tejasm-itpath** [comment]
@angelleye  Because of this issue we have faced that directory name problem with wc vendors pro version

**Comment by angelleye** [comment]
@tejasm-itpath I'm a little confused.  All you did here was change the directory name..??

**Comment by tejasm-itpath** [comment]
@angelleye  Yes, We were looking for the extension and change in it but real issue is in offers plugin where directory name is without "-"
