### ISSUE TITLE
PHP Fatal Error happening to some people..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#313]
* https://wordpress.org/support/topic/fatal-error-on-woocommerce-update/#topic-7476364-replies

Scroll to the end to see details about the issue.

**Comment by kcppdevelopers** [comment]
@angelleye 

When I Scroll to the end to see details like below :

yes i switched the themes and the error still occurred and even deactivated the plugins and still it dint go away

''even deactivated the plugins and still it dint go away'' It seems it not our plugin issue.

**Comment by angelleye** [comment]
>Thanks for the response
>Got the issue, one of the plugins led to the error i.e MediaPress
