### ISSUE TITLE
Tool tip needs to be updated:

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#318]
![image](https://user-images.githubusercontent.com/11312949/27371985-5ba455ee-567c-11e7-958c-a7d3495cf2f6.png)

if you can look here the tooltip don't add much help, if we can add an example of how the below percentage work, would be great.

> for example, let's say the price on the product is $100, but you would be willing to accept as low as $80
> you could use an auto-decline on anything 21% or higher
> that way any offer below 80 would auto-decline

Something self explanatory :)

**Comment by angelleye** [comment]
Upon further review, I really don't feel like a change was necessary here.  Closing.
