### ISSUE TITLE
WC vendors and WC vendors Pro Conflict: Plugin activation changes home page

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/offers-for-woocommerce#319]
When our plugin is active the Homepage is changed from home to blog.

Ref: https://www.angelleye.com/support/scp/tickets.php?id=1066

Using the most recent version of both plugins.

**Comment by tejasm-itpath** [comment]
@angelleye  @MansoorAliKhanOfficial  Tested and It is working now , You can test and release it now.
