### ISSUE TITLE
Notices and Contact conflict:

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#322]
Are we using any constant DS in our code? this might be creating conflict for one of our client, can you please take a look at this.?

> Notice: **Constant DS already defined** in /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-content/themes/santacruz/core/load.php on line 16
> 
> Notice: yith_wcwl_products cookie cannot be set - headers already sent by /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-content/themes/santacruz/core/load.php on line 16 in /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 735
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-content/themes/santacruz/core/load.php:16) in /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-includes/pluggable.php on line 1210
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-content/themes/santacruz/core/load.php:16) in /home/content/a2pewpnaspod04_data01/09/41195309/html/wp-includes/pluggable.php on line 1210

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  @angelleye  
No , We haven't use any constant like DS  in our code. and other Notices are from yith plugin so might be constant also came from it.
