### ISSUE TITLE
Swedish language causes failures..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#323]
* https://wordpress.org/support/topic/error-too-few-arguments-in-3/

When WP site language is set to Swedish we end up with a PHP failures.  More details at the link above.

**Comment by tejasm-itpath** [comment]
@angelleye 
Please see this link : https://www.screencast.com/t/3cDe5qoHcG
I have make my WP & Woocommerce & Offers Plugin to Swedish language 
And it is not sending us any error listed in the issues
Also Emails are looking perfect in swedish language https://www.screencast.com/t/OTNDu6Li3T3
