### ISSUE TITLE
wc_coupons_enabled : Issue 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#324]
https://wordpress.org/support/topic/wc_coupons_enabled-corrupted/

Can you please take a look here and see if it's something from our side and can provide a quick fix?

**Comment by MansoorAliKhanOfficial** [comment]
Anything on it?

**Comment by angelleye** [comment]
Nothing yet.  Tough to make this plugin a priority because there is no revenue generated from it.  We'll get to it as quickly as we can.

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan 
As Written in the  [Link](https://wordpress.org/support/topic/wc_coupons_enabled-corrupted/)
he is right, we should put condition under !is_admin() as our code will run only when it is view in frontend.

**Comment by iMansoorAliKhan** [comment]
I had already added that on my local setup and that worked for me, this very same condition also created conflict with one of other plugin created by WClovers.
So wrapping it inside ! is_admin worked for me
