### ISSUE TITLE
Adjustments for better compatibility with PayPal for WooCommerce

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#325]
When I have PayPal Express Checkout enabled on the product level as well as offers with history displayed at the product level, the EC button gets pushed down...

![image](https://user-images.githubusercontent.com/629241/27821177-08c91b76-6067-11e7-891b-8c66642002be.png)

We need to make sure our EC button always stays near the Add to Cart button.  Not sure if that's something we need to adjust here or in our PayPal for Woo plugin..??

**Comment by tejasm-itpath** [comment]
@angelleye @iMansoorAliKhan 
This is fixed 
https://www.screencast.com/t/PshDSe6ri6
