### ISSUE TITLE
OFFERS vendor account: Error

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#326]
![image](https://user-images.githubusercontent.com/11312949/27867894-72729f22-61b4-11e7-927b-53fe125ec0ef.png)

Use case:
The image captured when I submitted offer on my own product which I own as a vendor, so as per expectations it should not show offer option on my own, and the error also should be managed.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  I have tested this thing in my site in the same Flatsome theme. 
but i am not getting error like this. 
Offer has been sent successfully to the vendor itself. 
Error shown above is related to the theme or other template you have on the site. 
I am not facing any issue like this in my Flatesome theme. 
check the screenshot https://www.screencast.com/t/ODhefvJhVK

**Comment by tejasm-itpath** [comment]
@angelleye  If you want to add feature that vendor can not offer himself on his own products then we can add it.
What is your suggestion ?

**Comment by angelleye** [comment]
@tejasm-itpath Not sure why you're bringing that up here..??

**Comment by tejasm-itpath** [comment]
@angelleye 
For Example  Vendor1 has product "Google Pixel 2.0" and offer is enabled. So vendor1 can not make offer for his own product "Google Pixel 2.0".
So Do you want this feature in the plugin ??
because right now admin can also make offer to any product and Vendors can also make offers for any product.

**Comment by iMansoorAliKhan** [comment]
To clear this, If I have a listing in my store and have offers enabled then I should not see the offers button or alternately some other things to stop this, Same can be the case with the admin of the site.

**Comment by angelleye** [comment]
I'm still not sure I understand what you are reporting here.  Is this related to the original issue notes here?  

Can you provide some screenshots or a video to show me what you're reporting?

**Comment by iMansoorAliKhan** [comment]
Na, and I dont know why I saw that.
But it may be related to what TJ has said here

> @angelleye If you want to add feature that vendor can not offer himself on his own products then we can add it.
> What is your suggestion ?
This means that , When I, being store owner, visit my own product. Then I have the options to send offer to my own product. Better would be while loading the product it should check and hide the button if login user is the vendor or owner of the product.

![image](https://user-images.githubusercontent.com/11312949/32035533-77cde738-ba33-11e7-9d1b-e7419ca16c60.png)
Solde By: Oliver
Offer Submitted : Oliver
