### ISSUE TITLE
Offer for woo  | WC vendors Extension issues

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#327]
https://www.angelleye.com/support/scp/tickets.php?id=1329

Can you confirm this if these occur in main plugin or the VC extension?

- Vendor can delete offers before declining te offer (buyer gets no message)
- Buyer details are visible in pro dashboard after enabling that this should be not visble
- Vendor can include shipping with order but this not always matches the shipping configuration in the store.
- Stock: 1 (can be backordered) - product configuration stated that product cannot be backordered

**Comment by MansoorAliKhanOfficial** [comment]
Update on this: Client updated and some of the issues as we discussed over skype were fixed., still above needs to be tested and the following too.

The dashboards now function as expected. Buyer details are (if enable anonymous communication is on) no longer visible in de dashboard overview screens, but still visible on the offer page itself.
 

> We also found one other issue. If a new offer is made the vendor gets a email with the link like https://www.outletexclusive.nl/dashboard/woocommerce_offer/edit/8200 which works perfect. If the vendor makes a counter offer and the potential buyer then makes a counter offer on this the vendor gets a email but this email has the wrong link https://www.outletexclusive.nl/wp-admin/post.php?post=8200&action=edit instead of https://www.outletexclusive.nl/dashboard/woocommerce_offer/edit/8200.

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan 
https://github.com/angelleye/offers-for-woocommerce/issues/331
completed in #331

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  Other task are completed in https://github.com/angelleye/offers-for-woocommerce/issues/331
