### ISSUE TITLE
Offers for variations

### ISSUE THREAD

**Issue by holkakhol** [angelleye/offers-for-woocommerce#328]
* https://wordpress.org/support/topic/problem-with-variations-4/

Dear developers,
I think that i found little bug:
I try to create offer for variations product with some parameters (for example size and color), but offer creates for parent product (in offer management in product details i see parent sku and link to parent). I tried to use default theme, but it didn’t help =(
I tried to download previous version and noticed that variations works in ver 1.4.3, but stopped from version 1.4.5

**Comment by tejasm-itpath** [comment]
@angelleye  @holkakhol  @iMansoorAliKhan  
so here we need to display product details of the variable product for which offer has been sent + also need to give Parent link of the product ??

**Comment by tejasm-itpath** [comment]
now it will display Product detail of variable product for which it has selected .
https://www.screencast.com/t/yeOWRVvo1
@holkakhol  @angelleye  @iMansoorAliKhan
