### ISSUE TITLE
Option to set default expiration date.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#329]
We have a field where you can set an expiration date for an accepted or countered offer.  We need to add an option in the plugin settings where you can set a default expiration date.

**Comment by tejasm-itpath** [comment]
This is How I added to the Bulk tools 
https://www.screencast.com/t/oAmMW9o4CI

**Comment by angelleye** [comment]
@tejasm-itpath It looks like we actually already had this feature in place and I didn't realize it.  

I see that you added a Bulk Update for this, but we really don't need that.  As such, this issue branch can be ignored.
