### ISSUE TITLE
WC vendors Extension Option not working as expected.

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#330]
Please take a look at the following ticket, If you need to discuss we can talk over SLACK
https://www.angelleye.com/support/scp/tickets.php?id=1363

points:

1- the Option for hiding customer information is enabled in WC vendors extension under wp-admin > settings > Offer for woo
2- on dashboard shows " potential buyer"
3- but the link is still clickable so the vendor can see who is that potential buyer

Hope this will help escalate this  :)

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  
this issue is from Offers for Woo wc vendos extension and I have fixed it too in the commit.
Please see it. 
https://bitbucket.org/angelleye/offers-for-woocommerce-wc-vendors/issues/17/

**Comment by iMansoorAliKhan** [comment]
Hi, Per my testing the potential buyer thing is wokring.
There is 1 other thing as well should I add it here?
or create a new issue for that? The recent offers section displays title as users email not the title, is this intentional?
