### ISSUE TITLE
VC vendors extension : Styling and theme conflict

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#332]
testing with DIVI theme, the tabs to counter offer don't work.
tested with another theme the offer status select dropdown don't work.
tested on flatsome all ok but the select dropdown style if not ok. Please see the image.
![image](https://user-images.githubusercontent.com/11312949/28507129-d3bd9680-7049-11e7-8385-b11d74b1dba2.png)

the button saves offer also should have some proper name rather than save offer. if this is counter offer then it should say send counter offers etc.

![image](https://user-images.githubusercontent.com/11312949/28507149-fea5afb8-7049-11e7-8b9a-0854cc449630.png)
**Messages:** 	Offer saved successfully.  should be counter offer sent successfully.

**Comment by MansoorAliKhanOfficial** [comment]
Also , for offers and counter offer while WC vendors and vendors pro are active ; I dont receive any emails for those activities. though I received password change email but not the offer sent / received , counter offer sent / received... please take a look at that too.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan 
Can you tell me For which theme Select dropdown not working ?

**Comment by tejasm-itpath** [comment]
Commits will be added here
https://bitbucket.org/angelleye/offers-for-woocommerce-wc-vendors/issues/18/tabs-not-working-in-divi-and-other-themes

**Comment by iMansoorAliKhan** [comment]
Its was not only divi but almost 3 4 theme I tied, like the7, divi, and few other, I will give it an other try

**Comment by iMansoorAliKhan** [comment]
Okay That part is working now.

**Comment by angelleye** [comment]
@tejasm-itpath So this issue is ready for review then, right?  But the fix was actually done in the WC Vendors extension?

**Comment by tejasm-itpath** [comment]
@angelleye @iMansoorAliKhan 
Yes this is ready for review
