### ISSUE TITLE
Issue with Offer form on mobile devices

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#333]
https://wordpress.org/support/topic/bug-error-on-submit-offer-on-iphone/#post-9352973

https://files.slack.com/files-pri/T65BJLYF3-F6EK6EHL7/screenshot_20170726-004629.png

https://files.slack.com/files-tmb/T65BJLYF3-F6EK6EHL7-a537505297/screenshot_20170726-004629_720.png

On Mobile devices Android and iOS esp , the form is not loading properly hence people see error in submitting offers. Please take a look at above screenshots for references

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan 
I have made chnages to the condition as mentioned in the [question](https://wordpress.org/support/topic/bug-error-on-submit-offer-on-iphone/#post-9352973)

> I found it.
> 
> A successful request.statusText is HTTP/2.0 200 for iPhone, but it’s being compared to OK and success
> 
> 200 === request.status should be used in the condition in line 302 in public.js
> 
> I’ve given the fix already, so I’d appreciate it if you can apply the fix in the next immediate update. Thanks.
