### ISSUE TITLE
Issue with Woocommerce Simple Auctions and WC Vendors Pro Simple Auctions 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#338]
https://www.angelleye.com/support/scp/tickets.php?id=1458

**Comment by tejasm-itpath** [comment]
For this issue , I required following plugin.
- Woocommerce Simple Auctions
- WC Vendors Pro Simple Auctions

**Comment by angelleye** [comment]
@iMansoorAliKhan Can you get these things from the user for @tejasm-itpath ?

**Comment by iMansoorAliKhan** [comment]
@angelleye , I have responded to the ticket and requested both, I will update here when I will get a response.

**Comment by iMansoorAliKhan** [comment]
@angelleye, This issue can be closed as client responded that it's working for them, issue was due to some other plugins jQuery.

**Comment by angelleye** [comment]
@iMansoorAliKhan Go ahead and close this on your own when this sort of thing happens.  Just make sure to leave notes about why you're closing it when you do please.  Thanks!

**Comment by iMansoorAliKhan** [comment]
Okay, sure.
Thank you !
