### ISSUE TITLE
Some issue to menus from our code

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#340]
https://www.angelleye.com/support/scp/tickets.php?id=1474

> I am using Offer for WooCommerce - WC Vendors. I am using this with the WC Vendors and BuddyBoss Market Theme. Everything works fine except when I am logged in and on the My Account page. On this page it displays Recent Offers. On this page my menu items do not format correctly and the menus do not work correctly. I found the issue to this problem but do not know how to fix it. In the file my-offers.php the line $offer_args['product_url'] = $product->get_permalink(); is causing my menu issues. When I comment this line out the menus work and format fine. When this line is commented out, the Recent Offer section displays all offers in the system instead of just my offers.

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan 
I have tested in the BuddyBoss theme. 
Design looks perfect in the My Account tab. See the screenshot https://www.screencast.com/t/6GPEvNDZv3
Without commenting that line Menus and MyAccount page looks perfect and also display only recent offers.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan @angelleye 
If user share his screenshots before and after commenting the code then it would be good and quick for me to identify the bug

**Comment by iMansoorAliKhan** [comment]
I have responded to ticket for site URL to review it. Will update here on their reply
