### ISSUE TITLE
conflict with Paypal Plus

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#341]
Issue was discussed and tested with Tejas.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial What does that mean?  Is it fixed?  Does he still need to fix something?  What exactly is the issue?  Please be more clear notes when we add issues like this so we know what's going on when we look at this again in the future.

**Comment by MansoorAliKhanOfficial** [comment]
actually issue was that, when paypal plus is active and I , being buyer, had an offer accepted and is directed to pay, then when I click on pay it go to cart page then I click on proceed to checkout but its returned back to cart page with a message error processing checkout.
me and tejas diagnosed this but not fixed that is why added it here so its not skipped.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial  Okay, so yeah, if all you said was "issue discussed with Tejas" and then we don't see this again for a month or more we'd have no clue what it was about.  So please make sure to include such details in any issue you create in the future.  Thanks.

**Comment by MansoorAliKhanOfficial** [comment]
Yeah, sure I will. Sorry

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  
For PayPal Plus for WooCommerce , It is working.
I have set new Client Id and Client Secret and it is working. 
Please check your logs for proper error message. 
log file will be  your website directory ......./ wp-content/uploads/wc-logs/paypal_plus-....log
