### ISSUE TITLE
Feature Req - counteroffer alert, set min offer price, & form submit hook

### ISSUE THREAD

**Issue by digitsoft** [angelleye/offers-for-woocommerce#342]
**Counteroffer Alert**
Please add the option to have an alert pop up if the counter offer price isn't changed before sending to the buyer.

**Minimum Offer Price**
 If I have 3 items that are $200, $400, & $600, then there's no way I can set a percentage to make the minimum offer exactly $99 on all three.  Perhaps I could do it if manually adding a product 1 at a time, but not if I had to do it in bulk.

In my case I have multiple products created at the same time using an import plugin and my inventory changes weekly & monthly.  So having the option for a minimum offer based on percentage OR a set price is ideal.

**Form Submit Hook**
It the buyer enters an amount that is less than the minimum and auto-decline is enabled, then they still get to submit the form without being told what the minimum is.  This isn't good for a user experience and interrupts the sales flow.

Maybe the Submit button stays disabled until all required fields meet the criteria and the Price field goes red if it’s less than the minimum?

Maybe a hook like “submit_button_pre_post” where we could display a message and/or make the Price field red to show that’s what stopped it? This would open it up so that all fields could be checked before the offer form data is saved.

**Comment by angelleye** [comment]
@digitsoft Thanks for posting this here.  We'll certainly look to add these improvements in a future update.

**Comment by tejasm-itpath** [comment]
@angelleye  
for Minimum Offer Price , Adding compatibility with **Woo Product Add-Ons** plugin.

**Comment by angelleye** [comment]
@tejasm-itpath Still working on this one or is it ready for review?

**Comment by tejasm-itpath** [comment]
@angelleye  It is ready but I want to add some hooks here like "before_submit_offers" and "after_submit_offers". and Also want to manage code of auto accept and auto declined that is went wrong in some case so that I will test this issues when #349 completed

**Comment by angelleye** [comment]
@digitsoft We have added these features to the plugin and they will be included in the 1.4.8 release coming soon.  Thanks for your feedback!
