### ISSUE TITLE
Vendor dashbaord : Recent offer title

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#343]
![image](https://user-images.githubusercontent.com/11312949/31263653-159f6566-aa7d-11e7-9ef8-ecdff7423968.png)
I think the title should be senders name not the email?

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  @angelleye 
this issue will be done here 
https://bitbucket.org/angelleye/offers-for-woocommerce-wc-vendors/issues/19/vendor-dashbaord-recent-offer-title-343
