### ISSUE TITLE
disable Make Offer option automatically when the product is on sale

### ISSUE THREAD

**Issue by dubok2004** [angelleye/offers-for-woocommerce#344]
I would like to ask you about new feature. Could you please make it possible (in settings) to disable Make Offer option automatically when the product is on sale. I think it is needed feature.
Many thanks in advance.

**Comment by angelleye** [comment]
@dubok2004 Sure, we can add an option for that in a future update.  We'll get to that ASAP!

**Comment by tejasm-itpath** [comment]
@angelleye  @dubok2004 @iMansoorAliKhan  
Added this option under the Display Setting tab. 
Check the checkbox to enable this feature. 
https://www.screencast.com/t/pT3i589Gj2

**Comment by angelleye** [comment]
@tejasm-itpath Instead of putting this under Display Settings, I'd rather have this option under General Settings.

**Comment by angelleye** [comment]
@tejasm-itpath I went ahead and updated the verbiage, so please make sure to copy what I have when you move it to the General Settings tab.
