### ISSUE TITLE
Offer only for certain Variations?

### ISSUE THREAD

**Issue by zu** [angelleye/offers-for-woocommerce#345]
Is it possible to have offers only for variations?

I couldn't find  out how although Issue #328 seems to suggest it's possible.

I can't see an option to activate / deactivate offers on variant level.

Do I miss something?

**Comment by angelleye** [comment]
@zu, I'm very sorry for the delay getting back to you.  

It looks like we've gotten this functionality completed here in our GitHub code, but it's set to be included in the 1.4.8 update that we yet to release.  

We had set this project aside temporarily while we finished some other things, but now I've got somebody actively working on this again so we can get this next update released before long.  Hopefully within the next week or so.
