### ISSUE TITLE
Virtue premium Theme conflict with variations 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#347]
https://wordpress.org/support/topic/error-selection-required-select-product-options-above-before-making-new-offer
Ticket: https://www.angelleye.com/support/scp/tickets.php?id=1546

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  For these issue to solve,  Virtue premium Theme  is required.

**Comment by iMansoorAliKhan** [comment]
I have responded to their thread and asked them to provide the theme, as soon as he replies, I will ping you.
Thanks

**Comment by iMansoorAliKhan** [comment]
Hi @tejasm-itpath, I have shared the theme with you on Slack. I hope you can check this and resolve any issue found.
Thanks

**Comment by angelleye** [comment]
@iMansoorAliKhan You can attach things like that here for future reference.  That way if anybody else needs to grab it for testing they can too.

**Comment by tejasm-itpath** [comment]
@angelleye @iMansoorAliKhan  
Yes , There is issue related with the Virtue premium.

**Comment by iMansoorAliKhan** [comment]
@angelleye, You mean I should attach theme here?

**Comment by angelleye** [comment]
@iMansoorAliKhan Yes, you can just drag the zip file into the comment box and it will attach the theme here so it's available for us to work with.

**Comment by angelleye** [comment]
Looks like he already got this one resolved, but just for future reference it's good to include it.

**Comment by iMansoorAliKhan** [comment]
@angelleye , Sure, Here we go.
[virtue_premium.zip](https://github.com/angelleye/offers-for-woocommerce/files/1436700/virtue_premium.zip)

**Comment by iMansoorAliKhan** [comment]
@angelleye , is this merged into the release branch? or I will need to send the issue-347 code to the client?

**Comment by angelleye** [comment]
It would probably be best to wait until we get everything merged into dev at least.  I'm going to be reviewing with @tejasm-itpath soon, and then we'll get this official release pushed.
