### ISSUE TITLE
Input fields focus problem on IOS

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#348]
https://www.angelleye.com/support/scp/tickets.php?id=1537
Input fields focus problem on IOS:  The Phone is Iphone 8 - IOS 11.0.3

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  
I have discussed this issue with @iMansoorAliKhan  
in **iOS 11.0.3** and **iPhone 7** & **iPhone 7 plus.**  but I can not reproduce this issue. 

See this :
[Link1](https://files.slack.com/files-tmb/T65BJLYF3-F7P1CBUU9-3dd66f371f/06fd5fc6-d871-4214-99a9-4d9b7cf16aad_1024.jpg)

[Link2](https://files.slack.com/files-tmb/T65BJLYF3-F7PLPB353-4907867184/32217ba7-4b3b-4861-b23d-a4d0334f26a3_1024.jpg
)

**Comment by iMansoorAliKhan** [comment]
I have responded to the client about this and waiting for their feedback.
I'll update here soon.
Thanks

**Comment by angelleye** [comment]
Never heard back, so I closed the osTicket thread and I'm closing this thread as well.
