### ISSUE TITLE
Price ranges for auto-accept / auto-decline.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#35]
Add options in the product details where you can set price ranges for automatically accepting or declining  the offer.

**Comment by angelleye** [comment]
Probably should just use a percentage based setting, so if the offer is within x% it will auto accept or auto-decline if it's outside that margin.

**Comment by angelleye** [comment]
One of the other issues that has been merged into the release branch seems to be causing a conflict here.  It's quite a bit of code in the conflict, so I'm not sure what we need to keep.  

Please merge the release branch into the issue-35 branch and resolve the conflict that comes up when you do that.

**Comment by kcppdevelopers** [comment]
I have merge the release branch into the issue-35 branch and resolved the conflict.

**Comment by angelleye** [comment]
This isn't quite what I was expecting.

Instead of setting separate percentages for auto-accept and auto-decline I was thinking we would just have a single check box to enable "auto accept/decline" and a single percentage value to set.

For example, I might enable auto accept/decline by checking the box, and then set the percentage to 80%.  That way any offer that is at least 80% of the current product price would be auto-accepted, and any offer lower than 80% of the current product price would be auto-declined.

**Comment by angelleye** [comment]
Another thing we need to consider here is our bulk edit tool.  If you go to Settings -> Offers for WooCommerce -> Tools Tab, you'll see the bulk edit tool where people can easily enable/disable offers on multiple products based on filters.

We need to add the same sort of tool to enable/disable the auto-accept/decline functionality for products.  Not sure if that can be included in the current tool or if it would be better to create a second tool below the current one in the Tools tab.

Either way, I think we need to make sure and provide the bulk edit option for this feature.

**Comment by angelleye** [comment]
I am reopening this because after running some tests I realized my previous notes were incorrect.

We do indeed need 2 sets of checkbox / percentage input boxes; one for auto-accept and one for auto-decline.

That way I could setup an auto-accept, but then I could leave everything else along so I could manually manage that and submit counter-offers with the buyer.  

For example, somebody could enable auto-accept for anything at least 80% of the listed price, and auto-decline anything only 50% or lower, but then anything in between would left for manual management.
