### ISSUE TITLE
COmpatibility check for WC product Bundle

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#350]
Ticket: https://www.angelleye.com/support/scp/tickets.php?id=1519
Product used : https://wpclever.net/downloads/woocommerce-product-bundle
When Client have a WC product with Type As smart bundle which have many products included in a bundle.
Then when I make offer, let say , for 20$ where the original Bundle price is 500$ and the admin confirm the offer. Then I go to my front-end WC account page and click on pay for the accepted 20$ amount , on the cart page price for that product is 500$ again. Which is not the case.
Can you please look into this and see if we are able to make an adjustment for this.
Thanks

**Comment by angelleye** [comment]
@iMansoorAliKhan So basically we just need to make sure our Offers plugin is compatible with the Product Bundle plugin, right?

**Comment by tejasm-itpath** [comment]
@angelleye  Yes , I think so

**Comment by iMansoorAliKhan** [comment]
Per my testing, it dont, I have tested on client site where they have configure it and it dont work.
Becasue the product bundle is new product type added by that plugin.
So not sure if this is in our compatibility list or we need to make it explicitly.

**Comment by angelleye** [comment]
@iMansoorAliKhan You keep confusing me about this.  I think TJ understood my question and the answer is simply yes, as he said.

When you say that you tested this and it didn't work...that's exactly why we need to add compatibility for this plugin / product type.  Our Offers plugin simply isn't aware of that product type or something about how that plugin is working, so it's unable to apply the offer amount to those products.

So we just need to install that bundle plugin on a test site, setup a bundle product with offers enabled, and then run some tests to find the problem and fix it in our plugin.  Then it will be compatible, and that should also make it work fine in the WC Vendors extension.

**Comment by iMansoorAliKhan** [comment]
@angelleye , Ah, My bad, You are right.

**Comment by iMansoorAliKhan** [comment]
@angelleye , I have just tested on my local setup. It still dindot worked for me , the only thing that I found is that, when  a product is type bundle, then in offer form I dont see the amount input field, but it only shows the quantity, I think this can be the problem.
Here is screenshot,
![image](https://user-images.githubusercontent.com/11312949/32313353-53c065be-bfc4-11e7-9146-b4a63d3cedff.png)

after submitting, this is what buyer see, if the offer is accepted.
![image](https://user-images.githubusercontent.com/11312949/32313379-6e14bf0a-bfc4-11e7-9bba-a5a1a0cc2e04.png)

**Comment by tejasm-itpath** [comment]
[woo-product-bundle-premium.zip](https://github.com/angelleye/offers-for-woocommerce/files/1440891/woo-product-bundle-premium.zip)
@angelleye  @iMansoorAliKhan 
I can not reproduce the error with this plugin and Offers are working in every case.
I have tested this in Divi, & Storefront  theme.

**Comment by iMansoorAliKhan** [comment]
@tejasm-itpath , may be I you didnot checked it, 
Here is use case again.

> When Client have a WC product with Type As smart bundle which have many products included in a bundle.
> Then when I make offer, let say , for 20$ where the original Bundle price is 500$ and the admin confirm the offer. Then I go to my front-end WC account page and click on pay for the accepted 20$ amount , on the cart page price for that product is 500$ again. Which is not the case.
> Can you please look into this and see if we are able to make an adjustment for this.

I have again tested it on a fresh install, I agree that fields not showing could be a theme issue. But please read the scenario again and test it . It's not grabbing the accepted offer price for product type bundle.
