### ISSUE TITLE
Woocommerce Variations Table - Grid plugin Latest version compatibility issue

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/offers-for-woocommerce#352]
In our 1.4. 7 release , We have made compatibility with Woocommerce Variations Table - Grid (Version 1.3.4) plugin in #302 but After update in Version 1.3.10 of Woocommerce Variations Table - Grid not showing make offer button.
Before  : https://www.screencast.com/t/FUhMr1WdQo  (Version 1.3.4)
After : https://www.screencast.com/t/i3TBdEqeJU (Version 1.3.10)
Make Offer Button not displaying

**Comment by tejasm-itpath** [comment]
@angelleye  
I have checked with both the version of Woocommerce Variations Table - Grid.
In Previous version they have used **woocommerce_after_add_to_cart_button** hook that's why our "Make Offer" button automatically added after "Add to cart" but in New version (1.3.10) they have not used **woocommerce_after_add_to_cart_button** hook , and instead they are adding table using javascript code. So our "Make Offer" button will not display.

**Comment by angelleye** [comment]
@tejasm-itpath So they are removing the add to cart button entirely?  If our Offer button is associated with "after_add_to_cart" then I don't understand why anything they're doing with JS around that would cause a problem.  If the cart button is showing up and our button is based on that hook, then it should show up..??

**Comment by tejasm-itpath** [comment]
@angelleye  They have removed add to cart functionality as  WooCommerce doing with hooks.
They have created their custom code by adding add to cart button dynamically with Javascript.
At first they are adding their code with  woocommerce_after_add_to_cart_button  hook 
Now they are adding code in woocommerce_after_product_summary hook and empty add_to_cart button default place. so that our button will not found Woocommerce's hook of "Add To Cart" button
and Make offer is not displaying.
The way "Woocommerce Variations Table - Grid." plugin using now is totally wrong as per Woocommerce code standard.

**Comment by angelleye** [comment]
So it sounds like what they've done is not considered Woo Standard, would you agree, @tejasm-itpath?

**Comment by tejasm-itpath** [comment]
Yes @angelleye   I agree totally.

**Comment by angelleye** [comment]
@tejasm-itpath Is this an issue you found yourself or did somebody report this?

**Comment by tejasm-itpath** [comment]
@angelleye  I have found this issue by checking in their plugin's code. 
https://wordpress.org/plugins/woo-variations-table/
You can check that too in their main file.

**Comment by angelleye** [comment]
@tejasm-itpath Right, but why were you were looking at that plugin in the first place?  I'm just trying to figure out if this is something we really need to worry about right now or not..??  If we don't have any users reporting the conflict then we can probably just ignore it for now.

**Comment by tejasm-itpath** [comment]
yes @angelleye  , we can ignore it and no need to worry about this.
I am just explaining why this will not fix.
