### ISSUE TITLE
WordPress 4.9 Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#353]
* https://make.wordpress.org/core/2017/11/07/wordpress-4-9-field-guide/

**Comment by tejasm-itpath** [comment]
Tested with https://wordpress.org/news/2017/10/wordpress-4-9-beta-4/ And overall it is working 
Still we need to check with other plugins and theme which will be compatible it.
Right now i have only two plugins Woocommerce and Offers plugin.
