### ISSUE TITLE
Button Alignment Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#354]
As it stands now, our Offer button shows up below our PayPal buttons from the PayPal for WooCommerce plugin.  Ideally, the Offer button should show up immediately to the right of the Add to Cart, and then PayPal buttons would show up below that.

Here's how it is now....

![image](https://user-images.githubusercontent.com/629241/32718267-36e9dda6-c822-11e7-8740-a3713b5bee5f.png)

Here is how I would like it to look...

![image](https://user-images.githubusercontent.com/629241/32718307-5c753c14-c822-11e7-9446-e3c97a71edd6.png)

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  I have tested this issue in below theme with screenshot links.
- One social : https://www.screencast.com/t/Yt5ekM2u2 
- Divi Theme : https://www.screencast.com/t/AF7JAafjF 
- Storefront theme : https://www.screencast.com/t/d5KQghNmsJd 
- The 7 theme : https://www.screencast.com/t/i9Ov8ulJ 
- Avada Theme : https://www.screencast.com/t/Y9Szok5d

**Comment by angelleye** [comment]
@tejasm-itpath Something isn't right here.  After updating Offers on woo.angelleye.com I am seeing this:

![image](https://user-images.githubusercontent.com/629241/34069019-32ab632c-e20d-11e7-972a-c2ece7947f57.png)

So not only is the offer button on top of the PayPal Credit button, but for some reason the Express Checkout PayPal button isn't showing up at all now..??

**Comment by angelleye** [comment]
@tejasm-itpath There's a chance recent updates in the PayPal for Woo plugin caused this, so need to grab the dev branch of that plugin for testing please.
