### ISSUE TITLE
Option for admin show hide "Include Shipping with Offer" in vendors dashbaord

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#355]
'Include Shipping with Offer' can be optional (like a tick-box in admin dashboard) in order to show in the WC vendors dashboard.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  this issue you already created as #321

**Comment by iMansoorAliKhan** [comment]
Yeah, I;m sorry The user sent it again so I thought I should add it here.
I'm going to close this thread now.
