### ISSUE TITLE
offers option in vendor dashbord not working on Divi

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#357]
http://prntscr.com/hb32wy

The highlighted option dont work  with DIVI 3.0.51, 
can you chek this?

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan 
@angelleye 
This issue should be done in https://bitbucket.org/angelleye/offers-for-woocommerce-wc-vendors/issues/20/offers-tab-not-working-under-add-product
