### ISSUE TITLE
Conflict with PayPal RentenZahlung

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#359]
[23-Nov-2017 08:12:29 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_permalink() on boolean in /demo/wp-content/plugins/offers-for-woocommerce/public/views/my-offers.php:54
Stack trace:
#0 demo/wp-content/plugins/offers-for-woocommerce/public/class-offers-for-woocommerce.php(2188): include_once()
#1 demo/wp-includes/class-wp-hook.php(286): Angelleye_Offers_For_Woocommerce->ofw_woocommerce_after_my_account('')
#2 demo/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 demo/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /home/starrwxm/public_html/mansooralikhan.com/demo/wp-content/plugins/woocommerce/templates/myaccount/dashboard.php(64): do_action('woocommerce_aft...')
#5 /home/starrwxm/public_html/mansooralikhan.com/demo/wp-content/plugins/woocommerce/includes/wc-core-functi in /home/starrwxm/public_html/mansooralikhan.com/demo/wp-content/plugins/offers-for-woocommerce/public/views/my-offers.php on line 54

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  If this is plugin then Please provide plugin.

**Comment by iMansoorAliKhan** [comment]
Its own own plugin, I'm gonna send it over slack.

**Comment by angelleye** [comment]
@iMansoorAliKhan @tejasm-itpath Any update on this?  Need to get a milestone set on this if it's something we can fix.  If not, let's get it closed please.

**Comment by iMansoorAliKhan** [comment]
@angelleye I have shared the plugin with him on the same day.

**Comment by angelleye** [comment]
@tejasm-itpath Any update after you got the plugin to work with?

**Comment by tejasm-itpath** [comment]
@angelleye @iMansoorAliKhan  
I have tested this plugin with Offers and Offers extension. It doesn't give me Errors as it shows you.
So that I follow the errors mentioned above.
As per that I want to give some clarification
**Error :  Call to a member function get_permalink()   :** This error is thrown as the ID passed in **wc_get_product** function is not a product or possibly you have deleted that product and it still have offers on it. that's why **wc_get_product return false** and we **can not get permalink for the boolean return value.**

**Comment by angelleye** [comment]
@iMansoorAliKhan Can you confirm what @tejasm-itpath has said here?

**Comment by iMansoorAliKhan** [comment]
@angelleye , Yes, I am able to reproduce this error again, this is not a conflict I guess, as this error only logged when you try to go to my account dashboard page http://prntscr.com/hmt2kz,  

```
As per that I want to give some clarification
Error : Call to a member function get_permalink() : This error is thrown as the ID passed in wc_get_product function is not a product or possibly you have deleted that product and it still have offers on it. that's why wc_get_product return false and we can not get permalink for the boolean return value.
```
I am not sure about it but may be but if you take a look at screenshot that is the page when u visit, error is reported in the log

**Comment by iMansoorAliKhan** [comment]
Okay, After reset my site db completely , imported demo again, setup offers plugin and yes, Now I dont see the error, but 1 think I dont understand is that previously there was 1 product which was not having its permalink but that product was there in back end. Not sure why that error was being produced.

So I guess this can be closed now.
