### ISSUE TITLE
New / Counter offer email template PRO dashbaord URL change

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#361]
We have give static URL for pro-dashboard in the above mentioned email templates, need to get the URL set in WC vendors pro tab

**Comment by iMansoorAliKhan** [comment]
I have coded this like this.
```
# This need to be added on 2 files
# woocommerce-new-counter-offer & woocommerce-new-offer
<?php
     $wc_prd_vendor_options = get_option('wc_prd_vendor_options');
    if(class_exists('WCVendors_Pro')){
        $pro_dashboard_id = $wc_prd_vendor_options['dashboard_page_id']; // get page ID 
        $pro_dashboard_page_slug   = get_post( $pro_dashboard_id )->post_name; // get URL SLUG for the pro dashbaord and Pass         $pro_dashboard_page_slug to the SITE_URL in the template
    }
?>
```

**Comment by iMansoorAliKhan** [comment]
@angelleye Can this be sent to client for test, although this works as I have got this working.

**Comment by angelleye** [comment]
@iMansoorAliKhan Sure, but you'll need to send them this specific branch as it has not yet been merged into dev.

**Comment by iMansoorAliKhan** [comment]
Okay, I'm gonna send this to them, Thanks :)

**Comment by iMansoorAliKhan** [comment]
Client applied the fix and that fixed the issue, So this issue can be closed now.
Thank you!
