### ISSUE TITLE
Offers for unique items - should prefill the "Quantity" field with 1 and change/hide some fields/labels

### ISSUE THREAD

**Issue by dcgavril** [angelleye/offers-for-woocommerce#363]
I am trying to use the plugin for unique items so today the plugin is showing the "quantity" field and "Price each" for unique items. 

Can we have a check where:
- if stock is 1
- allow backorders is set to false
- "Limit Offer Quantity at Product Stock Quantity" is enabled

-> then : 
- the field "quantity" will be hidden and set to 1 by default
- the "Price each" field or label will be renamed to "Price"
- and "Price total" field will be hidden

or just disable "quantity" and "price each" and only leave "price total" enabled. (currently cannot be done from the admin panel, as the 2 fields are set to required by default)

Thanks.

**Comment by angelleye** [comment]
Hmmm...it sounds like all you need to do is enable the "sold individually" option available at the product level in WooCommerce.  maybe I'm not fully understanding what you're after, though..??

**Comment by dcgavril** [comment]
Actually you are right, my products where set to quantity 1 and no backorders enabled, but didn't had the option "sold individually" enabled, and they where showing on the offer form the quantity and price each. With the option "sold individually" it solves my issue, I'll just change the label "price each" to "offered price" or something like that. Anyway, I still believe that the offer form should set automatically to quantity 1 in case there's only 1 in stock and no backorders, but that's just an improvement.
Thank you for your help and this useful plugin !

**Comment by angelleye** [comment]
We'll look into this for our 1.4.9 update.  Thanks for the feedback!

**Comment by angelleye** [comment]
We discussed this internally and we feel that the Sold Individually option takes care of scenarios where there is only 1 unique item for any given product.  Defaulting to 1 in other cases is not something we feel will add much value at this point, but we may revisit this in the future.  We do appreciate the feedback!
