### ISSUE TITLE
Translation File Sync..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#369]
In #367 we made some adjustments to our default translation file template, but now our actual translation files that were already being included with the plugin our out-dated.  We need to look into how to get these synced up easily, and get anything new translated and included in each translation file.

**Comment by tejasm-itpath** [comment]
@angelleye 
 I have used Loco Translate plugin https://wordpress.org/plugins/loco-translate/
that excatly does what we need here. 
It sync translation file with plugin's default pot file and later we need to add translated. It is similar to poEdit software, pdEdit have paid version for WP Plugin but this plugin gives us free functionality.

**Comment by tejasm-itpath** [comment]
@angelleye 
At the starting of the File , Last-Translator name was as ` "Last-Translator: admin <emaplesa@gmail.com>\n"`
Now after changed it is as 

`"Last-Translator: admin <tejasm@itpathsolutions.co.in>\n"`

So that i am going to change it to 

> `"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"`

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/OFW-8
