### ISSUE TITLE
Styling issue after new update 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#370]
http://prntscr.com/hq67v7

Before update was looking great but now is not.

**Comment by iMansoorAliKhan** [comment]
Theme used is Flatsome latest, on a fresh install its still same. Even for RTL language as well ( if we are not supporting RTL then this screenshot can be ignored )
RTL: http://prntscr.com/hrrtzt
LTR: http://prntscr.com/hrrule
Position 2, Before Add to card: http://prntscr.com/hrrvau
Position to right of cart button  : http://prntscr.com/hrrvp6
Position After product Price: http://prntscr.com/hrrw4o
Position: After products tabs : http://prntscr.com/hrrwes

Also if I set Form Display Type as Lightbox I get following popup
http://prntscr.com/hrrxrb
Can we make this better?

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  Yes m, Let me make some more adjustments , I tried with Flatesome theme but if i change the position then it is not looking better in Divi and Storefront , So let me check by identifying the Theme and may be based on theme we can apply the CSS.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan 
@angelleye  

I have tested the issue with following theme and here are the screenshots 

One social theme : https://www.screencast.com/t/n3OoJapQ9s
Avada Theme : https://www.screencast.com/t/1iO2kzd4x
Divi Theme : https://www.screencast.com/t/nUCiMWMQ
Flatesome Theme : https://www.screencast.com/t/BT0FM6Uy23r
Salient Theme: https://www.screencast.com/t/elvFQQikEtr
Store Front Theme : https://www.screencast.com/t/mptXMaUsr
The 7 Theme : https://www.screencast.com/t/EJGbngpggAE

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan 
@angelleye  
Also tested with PayPal for WooCommerce plugin 

With PayPal For WooCommerce plugin

Divi Theme : https://www.screencast.com/t/Bvd3ZRDqKT9
Store Front Theme : https://www.screencast.com/t/adsL6kUnYHHs
Flatesome Theme : https://www.screencast.com/t/iwDKfnfFDB
Avada Theme : https://www.screencast.com/t/JJLDqrdA
One social Theme : https://www.screencast.com/t/ZkjPgG4r
Salient Theme : https://www.screencast.com/t/FLqHLSbnKT2F
The 7 Theme : https://www.screencast.com/t/CjXMKhmE

**Comment by iMansoorAliKhan** [comment]
Flatsome: http://prntscr.com/ht7cq9
Divi theme : Position Before card Button, and After Product price, After product tabs
1- http://prntscr.com/ht7dlb
2- http://prntscr.com/ht7e5d
3- http://prntscr.com/ht7ekk

**Comment by angelleye** [comment]
@tejasm-itpath Seems we've still got some problems here.

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  Above commit is working for every theme , please check it after last commit.

**Comment by iMansoorAliKhan** [comment]
What would be the difference between these 2 positions?
http://prntscr.com/i60ycd 
Becasuse for me both are looking after the add to card button like this. http://prntscr.com/i60zgh
Also the alignment should be same as the card button

**Comment by tejasm-itpath** [comment]
> What would be the difference between these 2 positions?
> http://prntscr.com/i60ycd
Yes.

Alignment is depends on themes.. So to align properly we should add css based on themes.
I have added the same class of add to cart button so design of the button will be same as add to cart button.

**Comment by angelleye** [comment]
@tejasm-itpath These problems seemed to have been introduced with our 1.4.8 update.  Before that we didn't seem to have these issues regardless of the theme, so we need to figure out what changed..??

**Comment by tejasm-itpath** [comment]
@angelleye  
I have reverted the CSS same as the previous version.
It was showing this way before... https://www.screencast.com/t/ofHbJSZm
Then In the #354 , We have made adjustments. 
After that we are working in this issue , I have maintain the #354 as it is and Also added more css that looks good. Just have Margin issue in Flatsome theme only.
You can check it with Divi, Storefront and other themes too.
Now if we reverted the code of #354 then again the Make offer button will not look in one line of Add to Cart button,

**Comment by iMansoorAliKhan** [comment]
hi, with new divi theme its still showing like this
![image](https://user-images.githubusercontent.com/11312949/36013778-09711fd2-0d88-11e8-81ad-31ef1225d1dc.png)

**Comment by iMansoorAliKhan** [comment]
I think something coming up from paypal for woo?
becasue when I move cursor to pp button then it hovers , like taking some padding. like this

http://prntscr.com/ic7jox

**Comment by angelleye** [comment]
@iMansoorAliKhan What if you disable the PayPal Credit button (but leave the regular EC button)?

**Comment by iMansoorAliKhan** [comment]
@angelleye  I have disabled the EC its still showing the same

**Comment by angelleye** [comment]
@iMansoorAliKhan Okay, so then if you disable EC entirely on the product page does it fix the Offer button?

**Comment by iMansoorAliKhan** [comment]
Nope, its dont

**Comment by tejasm-itpath** [comment]
I discuss with @angelleye  on call about this issue. Width of the Product detail page is different in all the themes. and we made adjustments in #354 due to this all needs to make little adjustments with css.
