### ISSUE TITLE
PHP Fatal Error in PHP 7.1.12..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#371]
* https://mail.google.com/mail/u/0/#inbox/160b8c0105697e8e

![image](https://user-images.githubusercontent.com/629241/34503044-131f0d56-efdc-11e7-829c-10ce677ca549.png)

**Comment by angelleye** [comment]
This seems to be happening only when viewing the My Account screen when signed in to the site.  I am waiting for verification from the user that reported this about whether or not the initial offers are working properly or not.

**Comment by D3thw0lf** [comment]
Having a similar issue in WP-Admin
```Fatal error: Uncaught Error: Call to undefined function get_current_screen() in /var/www/vhosts/httpdocs/wp-content/plugins/offers-for-woocommerce/admin/class-offers-for-woocommerce-admin.php:752 Stack trace: #0 /var/www/vhosts/httpdocs/wp-includes/class-wp-hook.php(288): Angelleye_Offers_For_Woocommerce_Admin->angelleye_ofwc_exclude_cpt_from_comments_clauses(Array) #1 /var/www/vhosts/httpdocs/wp-includes/plugin.php(244): WP_Hook->apply_filters(Array, Array) #2 /var/www/vhosts/httpdocs/wp-includes/class-wp-comment-query.php(853): apply_filters_ref_array('comments_clause...', Array) #3 /var/www/vhosts/httpdocs/wp-includes/class-wp-comment-query.php(395): WP_Comment_Query->get_comment_ids() #4 /var/www/vhosts/httpdocs/wp-includes/class-wp-comment-query.php(346): WP_Comment_Query->get_comments() #5 /var/www/vhosts/httpdocs/wp-includes/comment.php(226): WP_Comment_Query->query(Array) #6 /var/www/vhosts/httpdocs/wp-c in /var/www/vhosts/httpdocs/wp-content/plugins/offers-for-woocommerce/admin/class-offers-for-woocommerce-admin.php on line 752```

**Comment by iMansoorAliKhan** [comment]
@D3thw0lf , have you deleted any accepted offers from the backend? which were related to your account or for the user you are checking?

**Comment by D3thw0lf** [comment]
Nope. I installed it and activated it. At this point it breaks the WP Admin (after clicking on "activate") :)

**Comment by iMansoorAliKhan** [comment]
Can you tell me which theme or another plugin you have? did you tried by disabling all others ?  Can you switch to the basic twenty theme then check? Because I have just tested it on my local setup and it worked perfectly well with PHP version 7.2.0

**Comment by D3thw0lf** [comment]
Using the following additional plugins for Wordpress:
- WooCommerce Checkout Multi-Step
- WooCommerce Germanized
- WooCommerce Wishlist Plugin
- Customer Reviews for WooCommerce
- Checkout Address Autocomplete for WooCommerce
- Hyyan WooCommerce Polylang Integration

Theme is buyed on Themeforest called "Eldritch - An Epic Theme for Gaming and eSports"

**Comment by iMansoorAliKhan** [comment]
Did you tried what I suggested? 
Disable All these plugins and then check, 
Also, switch to basic WP Twenty Theme then check if you still seeing the same issue?

**Comment by D3thw0lf** [comment]
Have to check that later. But I'll try and respond asap.

**Comment by iMansoorAliKhan** [comment]
Please take your time and do let us know what you got

**Comment by angelleye** [comment]
Here's another user reporting the problem with the user account page, and they're on PHP 7.0.

* https://wordpress.org/support/topic/woocommerce-my-account-page-loading-blank

**Comment by tejasm-itpath** [comment]
@angelleye 
Me and @iMansoorAliKhan  tried to reproduce the error shown above. but we can't. We have checked in PHP version 7.2 also. 
As per the Error , When product object calling get_permalink() then it must be product object. when its not then it will throw this type of error. That's why I have added condition in above commit.

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/OFW-9
