### ISSUE TITLE
Bulk Minimum Offer Price - feature request

### ISSUE THREAD

**Issue by digitsoft** [angelleye/offers-for-woocommerce#372]
It's great and makes my life easier, but would be more complete (IMO) if there was a "Where" option like this:  WHERE "Minimum Price" (<|=|>) value

This would allow updating only items based on a current minimum price.

In my case I sometimes add items without a minimum and it would be great to only update those instead of all (the current only option).  I'm sure there could be other cases where I only want to update minimum prices for those with a specific current minimum.

**Comment by angelleye** [comment]
Hmmm...we do have that already.  Did you check the Target field?

![image](https://user-images.githubusercontent.com/629241/34907346-d7915694-f842-11e7-86a1-b5adb3b8777a.png)

**Comment by digitsoft** [comment]
Not Price - the current minimum offer.

**Comment by digitsoft** [comment]
Unless Price in the Where drop down means the minimum offer price.  In that case it's worth updating the text Price to Minimum Offer.

**Comment by angelleye** [comment]
hmmm...yeah, I need to play with this and re-work the labels.  It is a little bit confusing.  

We have Min Offer Price and Offer Price Type.  I think we we had this setup was that if you had Offer Price Type set to Price, then the Minimum Offer Price value would be set based on the Target and Where fields.

So then if you switched Offer Price Type to Percentage, the Minimum Offer Price label should change to Minimum Offer Percentage, and then based on the Target and Where fields it would set the min to the calculated price based on the percentage that was entered.

Again, I need play with it to make sure I'm even correct on that at this point.  I'm a little confused myself.  We'll definitely make this less confusing one way or another.
