### ISSUE TITLE
Datepicker-Format

### ISSUE THREAD

**Issue by chrwald** [angelleye/offers-for-woocommerce#376]
Initialising the datepicker without explicit date format causes trouble in countries, where the dateformat is not mm/dd/yy. The date isn't getting saved at all or the month and days might get switched. Dirty but simple js does the trick:

`
jQuery(document).ready(function () {
    $('#offer-expiration-date').datepicker({dateFormat: 'yy/mm/dd'});
});
`

Using this in a separate js file enqueued after jquery-ui.min.js solves this or me. Is there a chance to get this or somethin similar into the plugin? It's a bit annoying, to have to manually change this after every upadate.

**Comment by iMansoorAliKhan** [comment]
@chrwald sorry for the delay, we are looking into it and you will be replied soon by one of our tech guys.
Thanks!
