### ISSUE TITLE
Conflict with WooCommerce Name Your Price

### ISSUE THREAD

**Issue by helgatheviking** [angelleye/offers-for-woocommerce#398]
Having the Offers plugin enabled causes the Add to Cart button to be hidden for [Name Your Price](https://woocommerce.com/products/name-your-price/)-enabled products. 

![image](https://user-images.githubusercontent.com/507025/45895467-e20c4880-bd96-11e8-9470-465b4313e0f6.png)

This even happens on products where "make an offer" is _not_ enabled, because offers wraps _every_ product with markup. Name Your Price products commonly have a null price string (since the customer can enter their own price), Offers is then wrapping the add to cart button with a `<div class="ofwc_no_price_product>` whose CSS is `display: none;` and so for a Name Your Price product, the add to cart button is unnecessarily hidden.

![image](https://user-images.githubusercontent.com/507025/45895945-45e34100-bd98-11e8-90f9-8cf35c3c40b8.png)

Here's the reference in source that is causing the issue: https://github.com/angelleye/offers-for-woocommerce/blob/release/public/class-offers-for-woocommerce.php#L359

Would it be possible for you to conditionally add the offers markup only for products where "make an offer" is enabled? I believe that would resolve the issue. Alternatively a `$product->is_purchasable()` check there could work in place of a strict `$product->get_price() == ''` as NYP already filters `woocommerce_is_purchasable` for NYP-enabled products. 

Thanks!

**Comment by iMansoorAliKhan** [comment]
Hi @helgatheviking Thanks for the feedback, although we are not seeing any other reports of this sort , so I will quickly get this added to our backlog for further testing. Can you please provide the plugin you are testing our plugin with. Also, that plugin allowing custom pricing so you are not defining anything in the price field??

Also, we have already given that option to enable offers on whichever product you like. You can enable it for all of them by using out bulk edit tool or can simple assign it to individual products at product level. Did you checked that already?

**Comment by helgatheviking** [comment]
@iMansoorAliKhan I'm the author of Name Your Price and received a support ticket about the conflict yesterday. It's the only one I've received too, so I'm assuming it's not a particularly common issue. 

>Also, that plugin allowing custom pricing so you are not defining anything in the price field??

Correct. If a suggested or minimum price is set, my plugin will also save that in the price field. But those are optional fields so if there's no suggested or minimum price, then the price field is null.

>Also, we have already given that option to enable offers on whichever product you like.
Understood. Offers is _not_ enabled on the product in question. It really doesn't make any sense to enable offers _and_ NYP_ on the same product, so if that doesn't work, I am not concerned. But that's not the case here. Offers adds markup to _every_ product even when offers is not enabled for a specific product. This is the part that I think should be changed. 

I would propose that all of [these actions](https://github.com/angelleye/offers-for-woocommerce/blob/release/public/class-offers-for-woocommerce.php#L87-L105) should be wrapped in conditional logic and _only_ applied if "make an offer" is enabled for that product. 

If you provide an email address I will send a zip of the NYP plugin.

**Comment by iMansoorAliKhan** [comment]
@helgatheviking Thank you so much for clarifications, I think to provide more technical information here I would have to ask @angelleye to take a quick look and see if we can help with this situation.

You will be replied on this soon.

Thanks Again !

**Comment by iMansoorAliKhan** [comment]
@helgatheviking  To add up here, I also just ran some test with no price at all and our offers button still show, see this :

![image](https://user-images.githubusercontent.com/11312949/45914489-3da20900-be5f-11e8-8a01-e0b7c0586f4f.png)

So I think that's the point of conflict ? When NYP is active this is getting hidden somehow?

**Comment by helgatheviking** [comment]
@iMansoorAliKhan I'm not referring to the "make an offer" button. I am referring to the "add to cart" button, which in your screenshot is _not_ present. Offers is always hiding the "add to cart" button for products with no price, whether the Name Your Price plugin is activated or not. 

For regular products (like in your example), that's not an issue since the product has no price and is not purchasable. With a null price, even WooCommerce core doesn't show the add to cart button (though WC-core tests `is_purchasable()`... a condition which is filterable). For a Name Your Price-enabled product this is incorrect as products without a price are still purchasable once a customer enters a price.

Here's a NYP-enabled product with no price and "make an offer" *NOT* enabled for this product:
https://wc34-helgatheviking.c9users.io/product/simple-nyp/

Note that the "add to cart" button is not visible. This is the conflict that I am describing. Make an Offer is not enabled for this product, yet it is still modifying the markup. This is what my PR will correct. 

I've made you an admin on my test site (and sent the plugin via email).

**Comment by iMansoorAliKhan** [comment]
@helgatheviking  Thank you so much for explain that further, we will need to look into that. I will add this to our Backlog on Jira and will look into this further to see if there any any adjustments / compatibility release for NYP. 
Thanks!

**Comment by helgatheviking** [comment]
Hi @iMansoorAliKhan you're welcome! 

>if there any any adjustments / compatibility release for NYP.

The easiest adjustment that I can think of is what I proposed in my PR, specifically here:
https://github.com/angelleye/offers-for-woocommerce/pull/399/commits/1637ea52ae2d48654a2d7e78945b1ece795ec2ba

where I test if the product has "make an offer" enabled before adding the offer markup. 

I didn't do anything on the shop page, but I think you probably should do that same thing there too.

**Comment by iMansoorAliKhan** [comment]
Sure, But I will have to share this to our devs and see what they have to say on this. I will update you about this soon.

Thanks You for your collaboration :)

**Comment by iMansoorAliKhan** [comment]
Hi @helgatheviking , Our developer did look at your commit today and after merging it to our dev branch, it didn't solved the problem though. Do you have any other inputs on this? Could take another look and see if you can make it work the way you are saying, Because the proposed change didn't do any effect, though.

**Comment by iMansoorAliKhan** [comment]
> https://angelleye.atlassian.net/browse/OFW-24

**Comment by helgatheviking** [comment]
@iMansoorAliKhan I can confirm that 1637ea52ae2d48654a2d7e78945b1ece795ec2ba (and now https://github.com/helgatheviking/offers-for-woocommerce/commit/ed41def95ec88b54918f400d6cd64ba50dff95f6) resolves the problem. I can't always leave this instance running, but here is the result:

NYP is enabled. Make an Offer is not enabled. the Offer markup is _not_ displayed and so does not interfere with NYP.
https://wc34-helgatheviking.c9users.io/product/simple-nyp/

versus
Make an Offer is enabled and so the offer markup _is_ displayed:
https://wc34-helgatheviking.c9users.io/product/make-an-offer/

There's no reason to load your markup everywhere and by _not_ doing so you will automatically improve plugin cross-compatibility and probably page load times too.

**Comment by angelleye** [comment]
@iMansoorAliKhan Looks like something we need to create a ticket for.  Did you do that already?

**Comment by iMansoorAliKhan** [comment]
@angelleye  Yep, its the Name your price plugin ticket we have in our system. 
I have added the ticket reference 9 days ago : https://angelleye.atlassian.net/browse/OFW-24

**Comment by iMansoorAliKhan** [comment]
hi @helgatheviking Our developer merged your proposed changes but still that didnot fix the issue you were reporting, so may be you have any other suggestions on how your plugins is making the change so I will forward those remarks to the dev guys and see if that works.

**Comment by helgatheviking** [comment]
@iMansoorAliKhan thanks! I'll try to test it later. Is it in master or another branch? And do you have a staging site I could access? I could check your setup and see why it isn't resolving the issue for you, because it definitely is in my site above (which may or may not be active at the moment).
