### ISSUE TITLE
Counter Offer Flow

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#66]
I submitted a new offer, then sent a counter-offer from the admin panel to the buyer.  Then I did another counter from the buyer back to the site, and that's where things aren't flowing how I'd like.

Basically, the counter offer from the buyer is being treated as a brand new offer (for the most part).  I was sent to the regular offer form on the product page again, where I had to fill in all my details again.

Submitting this form triggered the same emails that I get with a new offer is created, and the subject even says "New Offer" as opposed to "Counter Offer".

We need a counter offer to go through an actual counter flow of some sort, where they don't have to re-enter their details, and the emails are specific to "counter".

**Comment by angelleye** [comment]
The actual offer record did remain as a single record that got updated with the counter, so that's good, but the email notifications and the flow were just like a new offer, and that's what needs to be adjusted.

**Comment by kcwebmedia** [comment]
**On new offer post create unique ID for offer, stored as postmeta value - to be used later for referencing a parent offer when buyer submits a 'counter offer'.**
 * Add unique ID to url params on 'counter offer' email out to buyer
 * Add check to verify unique ID on public offer form; error msg if not valid offer
 * Remove public form inputs (name,phone,company,email) if posting 'counter'; display the parent data instead

**As for email to admin on a 'counter'**
? - We should probably setup another email template to manage in WC email settings page.
