### ISSUE TITLE
Offer Detail - History

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#67]
Need to add the complete history of offers/counter-offers into the offer detail screen.  Right now I can only see the original offer data and the current status, but if there were counters in between I can't see that.

**Comment by kcwebmedia** [comment]
* Store offer detail BLOB string on new WP comment containing (quantity, price per, total, notes)
 * Add wp_insert_comment() with 'comment_type' = 'offer-counter-history'
  * admin counter offer
  * post new counter offer

* Output any 'Counter History' comments into new 'Counter History' panel on offer detail

* Make offer 'comments' to NOT include 'comment_type' = 'offer-counter-history'

**Comment by kcwebmedia** [comment]
? Simplest solution - maybe we can just add the QTY/PRICE/AMOUNT + NOTES within the comments that are already happening; we could include styles in the comments that have 'countering' details in them so they would stand out ?

**Comment by angelleye** [comment]
I just want a basic history table that shows each offer / counter-offer up to the current status.  Right now all I can see is the original offer and the current counter-offer (if any)...

![image](https://cloud.githubusercontent.com/assets/629241/10115622/19dcc598-63d4-11e5-910e-497015062e2f.png)

If there were any counter-offers back and forth between those, though, I can't see that.  For example...

* Buyer's original offer is QTY 1 at $50
* Seller counter-offers QTY 1 at $75
* Buyer counter-offers QTY 1 at $65
* Seller counter-offers QTY 2 at $50
* Buyer completes the purchase.

If that sort of thing were to happen I would only be able to see the first offer and the last offer.  I wouldn't be able to see the entire history of counter-offers between that, which could be helpful for the seller when managing offers.

We need to add a table of meta-data or a related table or something that tracks every step so we can display the history accordingly.
