### ISSUE TITLE
Mailing List Integration

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#7]
An an option to enable / disable MailChimp / ConstantContact opt-in to the offer form.

So the site owner would enable MailChimp or ConstantContact in the Offers for WooCommerce settings, and then the offer form would display an option for the buyer to join the mailing list at the same time the offer is submitted.  

It could be as basic as a "Join our Mailing List" check box that gets added to the offer form if MailChimp or ConstantContact are enabled (and configured).

**Comment by angelleye** [comment]
We could make this a premium extension.

**Comment by elarson** [comment]
It would be nice to have this for MailPoet also.

**Comment by angelleye** [comment]
@kcppdevelopers, let's go ahead and add this for MailPoet, too.

**Comment by angelleye** [comment]
On the offer form, the "join our mailing list" section could use some work.  This is what I currently see on my site/theme.

![image](https://cloud.githubusercontent.com/assets/629241/10384477/609c297e-6e01-11e5-8e95-9e07bec008c1.png)

I realize I could probably make it look better with some CSS adjustments in my child theme, and all themes will be different, but I think we can do something here to make it better by default.

For example, can we add this to a div that is centered nicely with a gray background and a little bit of a border?  Something to make it stand out a little bit more.  Maybe an email icon of some sort, too..??
