### ISSUE TITLE
Offer Details Inventory Management

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#73]
When looking at offer details for an item with inventory management on and the offer is for more than is available, it's just saying "out of stock."  It should say "not enough stock to fill this offer."

**Comment by angelleye** [comment]
Another weird thing here was that even when I did have enough to fill the offer it was still saying out of stock.  The out of stock message never initially showed up until I had adjusted the qty to force it, but once it did, it won't go away.

**Comment by kcwebmedia** [comment]
* Show red msg: 'Not enough in stock to fulfill this offer' instead of out of stock (unless back orders allowed)
