### ISSUE TITLE
Recent comments showing up in sidebar..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#96]
I'm seeing the recent comments included with the sidebar comments...

![image](https://cloud.githubusercontent.com/assets/629241/6034125/b959d6ea-abe4-11e4-9db1-14155d5f2a4a.png)

Not sure if this is related to the comments issue on the dashboard summary or not..??

**Comment by kcwebmedia** [comment]
Comments (Offer Notes) -- need to be stored as comments without post_id, and additionally commentmeta entries are needed for each comment -- Offer ID will be stored in commentmeta to relate the comments to the offer posts.

* Add commentmeta entry for every comment stored on Offer posts

**Comment by kcwebmedia** [comment]
This issue also solved #90
