### ISSUE TITLE
Email notification text formatting.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#97]
The email I got as the buyer when the seller countered my offer is adding back slashes in the note that the seller left.

>Can\'t go that low for just 2.

**Comment by angelleye** [comment]
Here's another example from the response back to the seller in a buyer-counter..

>I can do $30/each but that\'s it.

Probably need to check this in all email notifications.

**Comment by kcwebmedia** [comment]
* //DONE// - Strip slashes from offer notes in email templates (8)
