### ISSUE TITLE
Status Update Confusion..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#99]
I think we've talked about this already, but I'm not sure we have an issue for it or not..?

We need to adjust how offers are managed from the details page a little bit.  Here's an example of why...

I received an offer, and I was trying to submit a counter offer.  I clicked the counter button from the grid view, which took me to details, and then I adjusted the qty and price for my counter and clicked Update.  

Well, it was set to Accepted instead of Counter, so it simply accepted the buyer's original offer and treated it as if I simply accepted it from the start.  

I simply forgot to set that to Countered before I hit update, and I could see that happening to a lot of people.

**Comment by angelleye** [comment]
The good news is that I was able to go ahead and set the status to counter and update the offer again.  This triggered the counter email as expected, and the offer was now adjusted as I wanted.

Then, from the buyer side, I had already received an "accepted offer" email for my original offer, but now that the offer had been updated to countered, the Pay link from the accepted offer email still worked, but used the updated settings, which is good.

So we definitely have some adjustments to do here, but overall, the plugin handled things nicely.

**Comment by kcwebmedia** [comment]
I think you are mistaken. When an offer is ‘pending’, new, then the status SELECT field is selected on blank value and required. You must have already had it set to accepted. (It does not load the page already on accepted. Please test again.

**Comment by angelleye** [comment]
Yup, I think you're right.  Closing the issue.
